// Jenkinsfile for the knet CI (github) project
//  1-May-2023    Chrissie Caulfield    original version for running 'old-style' jobs
// 16-Jun-2023    me again              Move a lot of stuff into getBuildInfo() for tidiness
// 13-Jul-2023    guess who?            Make it fully pipelined

@Library(['GlobalLib@artem-devel-test', 'GithubLib@artem-devel-test', 'ProjectLib@artem-devel-test']) _

// Who we are
def project = 'ci-test'
def info = [:]

def withinlock()
{
    sh "date; sleep 60; date"
    println("Called with locking test on ${env.NODE_NAME}");
}

// Pipeline code starts here
pipeline {
    // Start on the main Jenkins node. Build jobs are distributed inside 'parallel' below
    agent { label 'built-in' }

    // Things that external jobs might want to influence
    parameters {
	string(name: 'bootstrap',   defaultValue: '0', description: 'Bootstrap the RPM repos')
	string(name: 'fullrebuild', defaultValue: '0', description: 'This is a full rebuild - do not publish RPM and do NOT update build code on the nodes')
    }

    stages {
	// First check we are allowed to run, then set some params for that run

	stage('Detect PR comment') {
		steps {
			script {
		    def runreason = ''
		    if (currentBuild.getBuildCauses().shortDescription.size() > 0) {
			runreason = currentBuild.getBuildCauses().shortDescription[0]
		    }
		    echo "Build cause: ${runreason}"

		    if (runreason.contains('skip ci') || runreason.contains('ci skip')) {
			currentBuild.result = 'ABORTED'
			env.PR_CI_SKIP = 'true'
		    } else {
			env.PR_CI_SKIP = 'false'
		    }
		}
		}
	}

	stage('skip comment') {
            when {
                expression { env.PR_CI_SKIP == 'true' }
            }
            steps {
                echo "SKIP PR comment was here"
                sh 'echo PR_SKIP'
            }
        }

	stage('Detect commit comment') {
		steps {
			script {
		    def lastCommit = sh(script: 'git log -1 --pretty=%B', returnStdout: true).trim()
			if (lastCommit.contains('[ci skip]') || lastCommit.contains('[skip ci]')) {
				currentBuild.result = 'ABORTED'
				env.COMMIT_CI_SKIP = 'true'
			}else{
				env.COMMIT_CI_SKIP = 'false'
			}
		}
		}
	}

	stage('skip comment') {
            when {
                expression { env.COMMIT_CI_SKIP == 'true' }
            }
            steps {
                echo "SKIP comment was here"
                sh 'echo SKIP'
            }
        }

	stage('Detect changes') {
	    steps {
		script {
		    def diffBase = env.CHANGE_TARGET ? "origin/${env.CHANGE_TARGET}" : 'HEAD~1'
		    env.CHANGED_FILES = sh(script: "git diff --name-only ${diffBase}...HEAD || git diff --name-only ${diffBase} HEAD", returnStdout: true).trim()
		    echo "Changed files:\n${env.CHANGED_FILES}"
		    env.BASH_FILES_CHANGED = env.CHANGED_FILES.split('\n').any { it.endsWith('.sh') } ? 'true' : 'false'
		}
	    }
	}

	stage('Build and Test') {
            when {
                expression { env.BASH_FILES_CHANGED == 'true' }
            }
            steps {
                echo "Bash files were changed, running tests..."
                sh 'echo Hello'
            }
        }

	stage('Action IF files NOT changed') {
            when {
                expression { env.BASH_FILES_CHANGED == 'false' }
            }
            steps {
                echo "Bash files WERE NOT changed."
                echo "Skipping tests, but doing something else instead..."
                sh 'echo "Running alternative script"'
            }
        }

	stage('Setup build env') {
	    steps {
		script {
		    getBuildInfo(project, info)
		}
	    }
	}

        // This is the main stage - building and testing
	stage('Main stage') {
	    when {
		// getAuthCheck (in getBuildInfo) will usually abort the job if permission is denied,
		// but this is an extra check.
		expression { info['authcheck'] == true && info['is_draft'] == false }
	    }

	    // All of the stages that actually do stuff
	    steps {
		script {

		    cleanWs(disableDeferredWipeout: true, deleteDirs: true)

		    RWLock(info, 'artem_testlock_5', 'WRITE', 'jenkinsfile', { withinlock() } )

		    // The 'short' test list
		    def voting = buildRunMap('voting', info, ['voting': true,
							  'nodelabel': 'test-voting',
							  'extravars': ['justforfun': 'BOO',
									'depbuildname': 'kronosnet',
									'depbuildversion': 'main',
									'install': 0]])

		    // def nonvoting = buildRunMap('nonvoting', info, ['voting': false,
			// 					'nodelabel': 'test-nonvoting',
			// 					'extravars': ['depbuildname': 'kronosnet',
			// 						      'depbuildversion': 'stable1-proposed']])

		    // def nonvoting_clang = buildRunMap('nonvoting-clang', info, ['voting': false,
			// 						    'nodelabel': 'test-nonvoting',
			// 						    'extravars': ['compiler': 'clang',
			// 								  'depbuildname': 'kronosnet',
			// 								  'depbuildversion': 'main',
			// 								  'install': 0,
			// 								  'title': 'CLANG test']])

		    // def covscan_kmain = buildRunMap('kmain-covscan', info, ['voting': true,
			// 						'nodelabel': 'covscan',
			// 						'extravars': ['depbuildname': 'kronosnet',
			// 							      'depbuildversion': 'main']])
		    // def covscan_kstable = buildRunMap('kstable-covscan', info, ['voting': true,
			// 						    'nodelabel': 'covscan',
			// 						    'extravars': ['depbuildname': 'kronosnet',
			// 								  'depbuildversion': 'stable1-proposed']])
		    // def buildrpms = buildRunMap('buildrpms', info, ['voting': false,
			// 					'nodelabel': 'test-buildrpms'])


		    // Run them (errors are caught in info[:])
		    try {
			parallel voting // + nonvoting + nonvoting_clang + buildrpms //+ covscan_kmain + covscan_kstable
		    } catch (err) {
			println("Jenkinsfile caught "+err)
			info['exception_text'] += "\nparallel error caught: {$err}\n"
		    }
		}
	    }
	}

        // Build the RPM/Coverity repos etc. If the job failed, this is what tells Jenkins
	stage('Post Stage') {
	    when {
		expression { info['authcheck'] == true && info['is_draft'] == false }
	    }
	    steps {
		postStage(info)
	    }
	}
    }

    // Finish up and send emails
    post {
	always {
	    projectFinishUp(info)
	}
    }
}
