// Update BaseOS on all freebsd nodes

@Library(['GlobalLib@ilias-devel', 'ProjectLib@ilias-devel']) _

def info = [:]
def project = 'update-freebsd-devel'

// Generate the run-list
def buildFullRunMap(Map info)
{
    def collectBuildEnv = [:]
    def nodeList = getLabelledNodes(info['packager'])
    def downnodes = getLabelledNodes('down')
    println('"Down" nodes: '+downnodes)

    for (n in nodeList) {
	def node = n
	if (!downnodes.contains(node)) {
	    collectBuildEnv[node] = {
		updateBSDdevel(node, info)
	    }
	}
    }

    return collectBuildEnv
}

pipeline {
    agent { label 'built-in' }

    stages {
        stage('update BaseOS') {
            steps {
		script {
		    info['project'] = project
		    info['packager'] = 'freebsd-devel'
		    getBuildInfoCommon(info)
		    info['state'] = 'success'
		    info['branch'] = ''
		    info['stages_run'] = 0
		    info['stages_fail'] = 0
		    info['stages_fail_nodes'] = ''

		    // Now do all of the other nodes
		    def updates = buildFullRunMap(info)
		    try {
			parallel updates
			info['state'] = 'completed'
		    } catch (err) {
			println("Jenkinsfile caught "+err)
			info['exception_text'] += "\nparallel error caught: {$err}\n"
			info['state'] = 'error'
		    }
		}
	    }
        }
    }

    // Finish up and send emails
    post {
	always {
	    projectFinishUp(info)
	}
    }
}
