#!/bin/sh

set -ev

case $build in
 coverity)
  echo "cov-build --dir=./cov $MAKE"
  cov-build --dir=./cov $MAKE $MAKEOPTS
  echo "cov-analyze --dir=./cov --wait-for-license $covoptions"
  cov-analyze --dir=./cov --wait-for-license $covoptions
  echo "cov-format-errors --dir=./cov --json-output-v7 cov.json"
  cov-format-errors --dir=./cov --json-output-v7 cov.json
  echo "cov-format-errors --dir=./cov --emacs-style > cov.txt"
  cov-format-errors --dir=./cov --emacs-style > cov.txt
 ;;
 rpm)
  echo "$MAKE rpm"
  $MAKE $MAKEOPTS rpm
 ;;
 *)
  echo "$MAKE"
  $MAKE $MAKEOPTS
 ;;
esac
