#!/bin/sh

set -e

BUILDDIR=$(pwd)
ARK_BRANCH=os-build
CACHEDIR=/srv/kcache

mkdir -p $CACHEDIR

if [ ! -d $CACHEDIR/kernel-ark ]; then
	cd $CACHEDIR
	git clone https://gitlab.com/cki-project/kernel-ark.git
	cd kernel-ark
	git remote add gfs2 git://git.kernel.org/pub/scm/linux/kernel/git/gfs2/linux-gfs2.git
	git remote add dlm git://git.kernel.org/pub/scm/linux/kernel/git/teigland/linux-dlm.git
fi

cd $CACHEDIR/kernel-ark

git checkout $ARK_BRANCH
git fetch origin
git fetch gfs2
git fetch dlm
git reset --hard origin/$ARK_BRANCH

cd $BUILDDIR
rsync -a $CACHEDIR/kernel-ark .
cd kernel-ark

git checkout -b ci-test
git merge --no-ff -m 'Automatic merge of gfs2/for-next and dlm/next' gfs2/for-next dlm/next

yum -y install system-sb-certs libpfm-devel libunwind-devel $(make dist-get-buildreqs | grep "Missing dependencies:" | cut -d":" -f2)

make dist-srpm

srcrpm=$(ls -1 redhat/rpm/SRPMS/kernel-*.src.rpm)
RPMBUILDOPTS="--without debug --without debuginfo --without doc"

CIRPMDIR=$(pwd)/ci-test-rpms
rm -rf $CIRPMDIR
mkdir -p $CIRPMDIR

rpmbuild \
	--define "_sourcedir $CIRPMDIR/SOURCES" \
	--define "_specdir $CIRPMDIR/SPECS" \
	--define "_builddir $CIRPMDIR/BUILD" \
	--define "_srcrpmdir $CIRPMDIR/SRPM" \
	--define "_rpmdir $CIRPMDIR/RPMS" \
	$RPMBUILDOPTS \
	-rb $srcrpm
