#!/bin/sh

echo ===== PACKAGE LIST =====
# BSD
if which pkg > /dev/null 2>&1; then
 pkg info
fi
# DEB
if which dpkg > /dev/null 2>&1; then
 dpkg -l
fi
# rpm
if which rpm > /dev/null 2>&1; then
 rpm -qa | sort -u
fi
echo ===== HOST INFO =====
echo "uname -a"
uname -a
