#!/bin/sh

set -e

. $HOME/ci-tools/ci-set-env

echo ===== current build env =====
env | sort
echo =============================

ci-build-info
ci-setup-rpm
ci-setup-src
ci-build-src
ci-tests-src
ci-install-src
