#!/bin/bash

set -e

project="$1"

if [ -z "$project" ]; then
	echo "no project specificed"
	exit 1
fi

covdir=/var/www/ci.kronosnet.org/coverity

(
	flock -e 200
	echo "Purging 0 byte files"
	find $covdir/ -type f -size 0 -print -delete

	echo "Purging empty dirs"
	find $covdir/ -type d -empty -print -delete

	cd $covdir/$project/

	# nodes
	for x in $(ls); do
		cd $x
		# builds
		for i in $(ls); do
			echo "Processing $i"
			cd $i
			if [ -d new ]; then
				cd new
				rm -f index.html
				ln -sf cov-index.html index.html
				cd ..
			fi
			cd ..
		done
		# remove old builds (keep last 20)
		builds="$(ls -1 | sort -n)"
		numbuilds="$(echo "$builds" | wc -l)"
		if [ "$numbuilds" -gt 20 ]; then
			purgenum=$((numbuilds - 20))
			candidates="$(echo "$builds" | head -n $purgenum)"
			for z in $candidates; do
				echo "Removing old build: $z"
				rm -rf $z
			done
		fi
		cd ..
	done

	exit 0
) 200>/tmp/ci-cov-repos.lock
