#!/bin/bash

set -e

BUILD=none
REPOSRC=none
ANVILSRC=none

. $HOME/ci-tools/ci-setup-anvil-vm-env

cleanup_simengine

echo "Destroying VMs (if any)"

for i in $ALLNODES $CACHENODES; do
 destroy_vm $i
done
