#!/bin/bash

set -ex

publish=/srv/publish/

sourcenode="$1"
sourcedir="$2"
destdir="$publish/$3"
transferset="$4"

mkdir -p "$destdir"
cd "$destdir"

case $transferset in
	rpm)
		preptar="$(echo cd $sourcedir \&\& rm -f ci-artifacts.tar \&\& find .  -name \"*.rpm\" \| tar -cvf ci-artifacts.tar -T -)"
	;;
	cov)
		preptar="$(echo cd $sourcedir/cov.html \&\& rm -f ../ci-artifacts.tar \&\& tar -cvf ../ci-artifacts.tar .)"
	;;
	*)
		echo "Unknown transfer set"
		exit 1
	;;
esac

mkdir -p "$destdir"
cd "$destdir"

ssh "$sourcenode".ci.kronosnet.org $preptar
scp "$sourcenode".ci.kronosnet.org:"$sourcedir"/ci-artifacts.tar  .
tar -xvpf ci-artifacts.tar
rm -f ci-artifacts.tar

exit 0
