#!/bin/sh

set -e

START_NODE_DIR=$HOME/bin

case $(uname -s) in
  *Linux) SHELL="/bin/bash -e"
  ;;
  *BSD) SHELL="/bin/tcsh -e"
esac

mkdir -p $START_NODE_DIR
cat $CITHOME/start_node.in | sed \
    -e "s^@HOME@^$HOME^g" \
    -e "s^@SHELL@^$SHELL^g" \
    -e "s^@START_NODE_DIR@^$START_NODE_DIR^g" \
    > $START_NODE_DIR/start_node
chmod 755 $START_NODE_DIR/start_node
