#!/bin/bash

# ENTRY POINT (done)

set -e

publish=/var/www/ci.kronosnet.org/

sourcenode="$1"
sourcedir="$2"
destdir="$publish/$3"
transferset="$4"

mkdir -p "$destdir"
cd "$destdir"

case $transferset in
	rpm)
		preptar="$(echo cd $sourcedir \&\& rm -f ci-artifacts.tar \&\& find .  -name \"*.rpm\" \| tar -cvf ci-artifacts.tar -T -)"
		lock="/tmp/ci-rpm-repos.lock"
		# this should help to keep PR dirs clean
		find "$destdir" -name "*.rpm" -exec rm -f {} \;
	;;
	cov)
		preptar="$(echo cd $sourcedir/cov.html \&\& rm -f ../ci-artifacts.tar \&\& tar -cvf ../ci-artifacts.tar .)"
		lock="/tmp/ci-cov-repos.lock"
	;;
	*)
		echo "Unknown transfer set"
		exit 1
	;;
esac

ssh "$sourcenode".ci.kronosnet.org $preptar

(
	flock -e 200
	scp "$sourcenode".ci.kronosnet.org:"$sourcedir"/ci-artifacts.tar  .
	tar -xvpf ci-artifacts.tar
	rm -f ci-artifacts.tar
) 200>$lock

exit 0
