#!/bin/sh

set -ev

if [ -n "$install" ] && [ "$install" = 1 ] && [ "x$build" != "xcoverity" ]; then
 installpath=/srv/$DEST/${ghprbActualCommit}
 case "$DEST" in
  sbd|booth)
   installpath=${installpath}-pcmk-${pcmkver}/
   ;;
  *)
   installpath=${installpath}/
   ;;
 esac
 echo rm -rf $installpath
 rm -rf $installpath
 if [ "$DEST" = "pcmk" ]; then
  echo "$MAKE clean"
  $MAKE clean
  echo "./configure --prefix=$installpath --exec-prefix=$installpath --sysconfdir="$installpath/etc" --with-initdir="$installpath/etc/init.d" --with-ocfdir="$installpath/lib/ocf"  --with-systemdsystemunitdir="$installpath/usr/lib/systemd/system" $DISTROCONFOPTS PKG_CONFIG_PATH=$EXTERNAL_CONFIG_PATH"
  ./configure --prefix=$installpath --exec-prefix=$installpath --sysconfdir="$installpath/etc" --with-initdir="$installpath/etc/init.d" --with-ocfdir="$installpath/lib/ocf"  --with-systemdsystemunitdir="$installpath/usr/lib/systemd/system" $DISTROCONFOPTS PKG_CONFIG_PATH=$EXTERNAL_CONFIG_PATH
  echo "$MAKE $MAKEOPTS"
  $MAKE $MAKEOPTS
 fi
 echo "$MAKE $MAKEINSTALLOPTS install"
 $MAKE $MAKEINSTALLOPTS install
 echo "https://ci.kronosnet.org/job/$JOB_NAME/$BUILD_NUMBER/consoleFull" > $installpath/.build-info
 echo "Creating cross projects symlinks hacks for pcs testing"
 case "$DEST" in
  pcmk)
   cd $installpath/lib/ocf
   rm -f lib
   ln -sf /srv/ras/origin/master/lib/ocf/lib
   cd resource.d
   rm -f heartbeat
   ln -sf /srv/ras/origin/master/lib/ocf/resource.d/heartbeat
   cd pacemaker
   rm -f booth-site
   if [ "${ghprbActualCommit}" = "origin/master" ]; then
    ln -sf /srv/booth/origin/master-pcmk-master/lib/ocf/resource.d/pacemaker/booth-site
   else
    ln -sf /srv/booth/origin/master-pcmk-2.1/lib/ocf/resource.d/pacemaker/booth-site
   fi
  ;;
 esac
fi
