#!/bin/sh

set -ev

if [ -n "$install" ] && [ "$install" = 1 ]; then
 echo rm -rf /srv/$DEST/${ghprbActualCommit}/
 rm -rf /srv/$DEST/${ghprbActualCommit}/
 echo "$MAKE $MAKEOPTS install"
 $MAKE $MAKEOPTS install
 echo "https://ci.kronosnet.org/job/$JOB_NAME/$BUILD_NUMBER/consoleFull" > /srv/$DEST/${ghprbActualCommit}/.build-info
fi
