#!/bin/sh

set -e

tempfile=$(mktemp /tmp/XXXXXXXX.json)

wget -O $tempfile "http://ci.kronosnet.org/computer/api/json?pretty=true"

nodelist="$(cat $tempfile | jq '.computer' | grep displayName | sed -e 's/.*": "//g' -e 's/",//g' |grep -v ^master$)"
reconnectlist="$(echo $nodelist | sed -e 's/ /,/g')"

for node in $nodelist; do
	echo disconnecting node $node
	./jcli disconnect-node $node
done

./jcli connect-node $reconnectlist

rm -rf $tempfile
