#!/bin/sh

set -e

trap cleanup EXIT

cleanup() {
	[ -n "$tempfile" ] && rm -rf $tempfile
}

connect="$1"

nodelist=$(ls -1 $HOME/nodes)

for node in $nodelist; do
	echo disconnecting node $node
	n=0
	while [ $(./jcli disconnect-node $node) ] && [ "$n" -lt 5 ]; do
		echo "Retrying disconnect"
		n=$(expr $n + 1)
	done
done

if [ -n "$connect" ]; then
	for node in $nodelist; do
		echo connecting node $node
		./jcli connect-node $node
	done
fi
