#!/bin/sh

set -ev

. /root/ci-tools/ci-rpm-common

if [ "$build" = rpm ] || [ "$DEST" = pcmk1 ]; then
 if [ -n "$RPMDEPS" ]; then
  echo "Installing rpm deps: $RPMDEPS"
  installrpmdeps
 else
  echo "No rpm deps requested"
 fi
fi
