#!/bin/sh

set -ev

case "$DEST" in
 gfs2-*|dlm)
  if [ -n "$REPO" -a -n "$BRANCH" ]; then
   git config user.email "jenkins@kronosnet.org"
   git config user.name "Sir Jenkins"
   git remote rm proposed || true
   git remote add proposed "$REPO"
   git fetch proposed
   git checkout "origin/${BRANCH_TO:-main}"
   git merge --no-ff "proposed/$BRANCH" -m "Merge PR"
  fi
 ;;
esac

if [ -f ./autogen.sh ]; then
 echo "./autogen.sh"
 ./autogen.sh
fi

if [ -f ./configure ]; then
 # workaround bug in pacemaker test suite
 case "$DEST" in
  pcmk)
   echo "./configure $DISTROCONFOPTS PKG_CONFIG_PATH=$EXTERNAL_CONFIG_PATH"
   ./configure $DISTROCONFOPTS PKG_CONFIG_PATH=$EXTERNAL_CONFIG_PATH
   ;;
  pcs)

   sleeptimer=$(( $$ % 240 ))
   echo "Random sleep: $sleeptimer"
   sleep $sleeptimer

   case "${NODE_NAME}" in
    debian*|ubuntu*)
     localbuild=""
     usesitepackages=--system-site-packages
     ;;
    rhel8*|centos-8*|opensuse-15*)
     localbuild=--enable-local-build
     usesitepackages=--system-site-packages
     ;;
    *)
     localbuild=--enable-local-build
     usesitepackages=""
     ;;
   esac
   rm -rf .venv
   python3 -m venv $usesitepackages .venv
   . .venv/bin/activate
   export PATH="$(pwd)/.venv"/bin/:$PATH
   python3 -m pip install setuptools-scm setuptools-rust wheel
   python3 -m pip install concurrencytest cryptography lxml pycurl six pyparsing
   echo "./configure --enable-destructive-tests --enable-parallel-tests $localbuild $DISTROCONFOPTS PKG_CONFIG_PATH=$EXTERNAL_CONFIG_PATH"
   ./configure --enable-destructive-tests --enable-parallel-tests $localbuild $DISTROCONFOPTS PKG_CONFIG_PATH=$EXTERNAL_CONFIG_PATH
   ;;
  *)
   installpath=/srv/$DEST/${ghprbActualCommit}
   case "$DEST" in
    knet|corosync)
     if [ -n "$RUSTBINDINGS" ] && [ "$RUSTBINDINGS" = yes ]; then
      extraopts="--enable-rust-bindings"
     fi
     ;;
    sbd)
     installpath=${installpath}-pcmk-${pcmkver}/
     ;;
    booth)
     installpath=${installpath}-pcmk-${pcmkver}/
     extraopts="--with-ocfdir=$installpath/lib/ocf"
     ;;
    gfs2-*)
     case "${NODE_NAME}" in
      *x86*)
       extraopts="--with-testvol=/dev/shm/testvol-${BUILD_NUMBER}"
      ;;
     esac
     ;;
    *)
     installpath=${installpath}/
     ;;
   esac
   echo "./configure --prefix=$installpath --exec-prefix=$installpath $extraopts $DISTROCONFOPTS PKG_CONFIG_PATH=$EXTERNAL_CONFIG_PATH"
   ./configure --prefix=$installpath --exec-prefix=$installpath $extraopts $DISTROCONFOPTS PKG_CONFIG_PATH=$EXTERNAL_CONFIG_PATH
   ;;
 esac
fi
