#!/bin/sh

set -e

if [ -f ./autogen.sh ]; then
 echo "./autogen.sh"
 ./autogen.sh
fi

if [ -f ./configure ]; then
 # workaround bug in pacemaker test suite
 case "${project}" in
  pacemaker)
   echo "./configure $DISTROCONFOPTS PKG_CONFIG_PATH=$EXTERNAL_CONFIG_PATH"
   ./configure $DISTROCONFOPTS PKG_CONFIG_PATH=$EXTERNAL_CONFIG_PATH
   ;;
  pcs)

   sleeptimer=$(( $$ % 240 ))
   echo "Random sleep: $sleeptimer"
   sleep $sleeptimer

   rm -rf .venv
   python3 -m venv --system-site-packages .venv
   . .venv/bin/activate
   export PATH="$(pwd)/.venv"/bin/:$PATH

   case "${NODE_NAME}" in
    debian*|ubuntu*)
     localbuild=""
     ;;
    rhel-8*)
     python3 -m pip install concurrencytest
     localbuild=--enable-local-build
     ;;
    *)
     localbuild=--enable-local-build
     ;;
   esac

   echo "./configure --enable-destructive-tests --enable-parallel-tests $localbuild $DISTROCONFOPTS PKG_CONFIG_PATH=$EXTERNAL_CONFIG_PATH"
   ./configure --enable-destructive-tests --enable-parallel-tests $localbuild $DISTROCONFOPTS PKG_CONFIG_PATH=$EXTERNAL_CONFIG_PATH
   ;;
  *)
   installpath=/srv/${project}/origin/${target}
   case "${project}" in
    kronosnet|corosync)
     if [ -n "$RUSTBINDINGS" ] && [ "$RUSTBINDINGS" = yes ]; then
      extraopts="--enable-rust-bindings"
     fi
     ;;
    sbd)
     installpath=${installpath}-pacemaker-${pacemakerver}/
     ;;
    booth)
     installpath=${installpath}-pacemaker-${pacemakerver}/
     extraopts="--with-ocfdir=$installpath/lib/ocf"
     ;;
    *)
     installpath=${installpath}/
     ;;
   esac
   echo "./configure --prefix=$installpath --exec-prefix=$installpath $extraopts $DISTROCONFOPTS PKG_CONFIG_PATH=$EXTERNAL_CONFIG_PATH"
   ./configure --prefix=$installpath --exec-prefix=$installpath $extraopts $DISTROCONFOPTS PKG_CONFIG_PATH=$EXTERNAL_CONFIG_PATH
   ;;
 esac
fi
