#!/bin/sh

set -e

. $CITHOME/ci-rpm-common

if [ "$build" = "rpm" ]; then
 if [ -n "$RPMDEPS" ]; then
  echo "Installing rpm deps: $RPMDEPS"
  installrpmdeps
 else
  echo "No rpm deps requested"
 fi
fi
