#!/bin/sh

set -ev

cleanlibqb() {
 # libqb test suite will leave craft behind in case of failures
 # make sure to clean before and after the test run
 if [ "$DEST" = libqb ]; then
  if [ -d "/dev/shm" ]; then
   find /dev/shm -type d -name qb-test\* |xargs rm -rf
  fi
  rm -rf /tmp/libqb-*
 fi
}

case $build in
 rpm)
  exit 0
  ;;
 coverity)
  echo "===== CURRENT COVERITY SCAN ERRORS ====="
  cat cov.txt
  echo "===== END CURRENT COVERITY SCAN ERRORS ====="

  ret=0
  # this will trigger only with build-after-merge
  if [ "${install}" = 1 ]; then
   mkdir -p /srv/covscan/$DEST/$GIT_BRANCH/
   mv cov.json cov.txt /srv/covscan/$DEST/$GIT_BRANCH/
  else
   csdiff -xc --no-color /srv/covscan/$DEST/$TARGET/cov.json cov.json > cov.diff
   errors="$(cat cov.diff | grep ^Error: | wc -l)"
   if [ "$errors" -ne "0" ]; then
    echo "===== NEW COVERITY SCAN ERRORS FIXED ====="
    cat cov.diff
    echo "===== END NEW COVERITY SCAN ERRORS FIXED ====="
   fi
   csdiff -c --no-color /srv/covscan/$DEST/$TARGET/cov.json cov.json > cov.diff
   errors="$(cat cov.diff | grep ^Error: | wc -l)"
   if [ "$errors" -ne "0" ]; then
    echo "===== NEW COVERITY SCAN ERRORS DETECTED ====="
    cat cov.diff
    echo "===== END NEW COVERITY SCAN ERRORS DETECTED ====="
    ret=1
   fi
  fi

  exit $ret
  ;;
 *)
  ;;
esac

if [ -n "$CHECKS" ] && [ "$CHECKS" = "crosscompile" ]; then
 if [ "$(find . -print -type f -exec file {} \; | grep ELF | grep $ARCH | wc -l)" = 0 ]; then
  echo "Crosscompilation test failed. Unable to find any $ARCH binaries"
  exit 1
 fi
 exit 0
fi

cleanlibqb

if [ -z "$CHECKS" ]; then
 CHECKS="check distcheck $EXTRACHECKS"
fi

for i in $CHECKS; do
 echo "$MAKE $i DISTCHECK_CONFIGURE_FLAGS="$DISTROCONFOPTS" || (find . -name "*test-suite.log" -exec cat {} \; ; false)"
 $MAKE $i DISTCHECK_CONFIGURE_FLAGS="$DISTROCONFOPTS" || (find . -name "*test-suite.log" -exec cat {} \; ; false)
done

cleanlibqb
