#!/bin/sh

set -e

cleanlibqb() {
 # libqb test suite will leave craft behind in case of failures
 # make sure to clean before and after the test run
 # this code works because we do NOT allow multiple builds of libqb
 # in parallel!
 if [ "${project}" = libqb ]; then
  if [ -d "/dev/shm" ]; then
   find /dev/shm -name qb-\*-test\* | xargs rm -rf
  fi
  find /tmp -type d -name libqb\* | xargs rm -rf
 fi
}

pacemakerextratests() {
 # pacemaker extra tests
 if [ "${project}" != pacemaker ]; then
  return
 fi
 ./cts/cts-regression -V
}

case $build in
 rpm)
  exit 0
  ;;
 coverity)
  echo "===== CURRENT COVERITY SCAN ERRORS ====="
  cat cov.txt
  echo "===== END CURRENT COVERITY SCAN ERRORS ====="

  ret=0
  # this will trigger only with build-after-merge
  if [ "${install}" = 1 ] || [ "${covinstall}" = 1 ]; then
   mkdir -p /srv/covscan/${project}/origin/${target}/$extraver/
   rm -f /srv/covscan/${project}/origin/${target}/$extraver/cov*
   cp cov.json cov.txt /srv/covscan/${project}/origin/${target}/$extraver/
  else
   if [ ! -d /srv/covscan/${project}/origin/${target} ]; then
    echo "WARNING: target branch origin/${target} no available for compare. Skipping."
    exit 0
   fi
   csdiff -xc --no-color /srv/covscan/${project}/origin/${target}/$extraver/cov.json cov.json > cov.diff
   errors="$(cat cov.diff | grep ^Error: | wc -l)"
   if [ "$errors" -ne "0" ]; then
    echo "===== NEW COVERITY SCAN ERRORS FIXED ====="
    cat cov.diff
    echo "===== END NEW COVERITY SCAN ERRORS FIXED ====="
   fi
   csdiff -c --no-color /srv/covscan/${project}/origin/${target}/$extraver/cov.json cov.json > cov.diff
   errors="$(cat cov.diff | grep ^Error: | wc -l)"
   if [ "$errors" -ne "0" ]; then
    echo "===== NEW COVERITY SCAN ERRORS DETECTED ====="
    cat cov.diff
    echo "===== END NEW COVERITY SCAN ERRORS DETECTED ====="
    ret=1
    mkdir cov.html/new
    cat cov.diff | cshtml - > cov.html/new/index.html
   fi
  fi

  exit $ret
  ;;
 crosscompile)
  if [ "$(find . -print -type f -exec file {} \; | grep ELF | grep $ARCH | wc -l)" = 0 ]; then
   echo "Crosscompilation test failed. Unable to find any $ARCH binaries"
   exit 1
  fi
  exit 0
  ;;
 *)
  ;;
esac

if [ -n "$CHECKS" ] && [ "$CHECKS" = "nochecks" ]; then
 exit 0
fi

# blacklist PARALLELMAKE as necessary
if [ -n "$PARALLELTEST" ] && [ "$PARALLELTEST" = "no" ]; then
  echo "${project} does not support parallel test. disabling PARALLELMAKE"
  export PARALLELMAKE=""
fi

case "${project}" in
 pcs)
  case "${NODE_NAME}" in
   debian*|ubuntu*)
    localbuild=""
    ;;
   *)
    localbuild=--enable-local-build
    ;;
  esac
  if [ -f .venv/bin/activate ]; then
   . .venv/bin/activate
   export PATH="$(pwd)/.venv"/bin/:$PATH
  fi
  $MAKE $PARALLELMAKE check
  $MAKE $PARALLELMAKE distcheck DISTCHECK_CONFIGURE_FLAGS="--enable-parallel-tests --enable-destructive-tests $localbuild $DISTROCONFOPTS PKG_CONFIG_PATH=$EXTERNAL_CONFIG_PATH"
  exit 0
 ;;
 booth)
  extraopts="--with-ocfdir=\$$\{prefix\}/lib/ocf"
 ;;
 kronosnet|corosync)
  if [ -n "$RUSTBINDINGS" ] && [ "$RUSTBINDINGS" = yes ]; then
   extraopts="--enable-rust-bindings"
  fi
 ;;
esac

if [ -z "$CHECKS" ]; then
 CHECKS="check distcheck $EXTRACHECKS"
fi

if [ -n "$TESTUSELDPATH" ] && [ "$TESTUSELDPATH" = yes ]; then
 echo "export LD_LIBRARY_PATH=$EXTERNAL_LD_LIBRARY_PATH"
 export LD_LIBRARY_PATH=$EXTERNAL_LD_LIBRARY_PATH
fi

for i in $CHECKS; do
 cleanlibqb
 echo "$MAKE $PARALLELMAKE $MAKETESTOPTS $i DISTCHECK_CONFIGURE_FLAGS="$extraopts $DISTROCONFOPTS" PKG_CONFIG_PATH=$EXTERNAL_CONFIG_PATH || (find . -name "*test*suite.log" -exec cat {} \; ; false)"
 $MAKE $PARALLELMAKE $MAKETESTOPTS $i DISTCHECK_CONFIGURE_FLAGS="$extraopts $DISTROCONFOPTS" PKG_CONFIG_PATH=$EXTERNAL_CONFIG_PATH || (find . -name "*test*suite.log" -exec cat {} \; ; false)
done

cleanlibqb
pacemakerextratests
