#!/bin/sh

set -e

cd /root

$HOME/ci-tools/ci-update-common

if [ -z "$1" ]; then
 freebsd-update --not-running-from-cron fetch
 freebsd-update --not-running-from-cron install || true
 pyver=39
 rustextradeps=""
else
 pyver=39
 rustextradeps=""
fi

if [ -n "$RUSTBINDINGS" ] && [ "$RUSTBINDINGS" = yes ]; then
 rustdeps="rust rust-bindgen-cli $rustextradeps"
fi

pkg upgrade -y
pkg install -y rsync git gcc automake autoconf autotools pkgconf gettext gettext-tools nss libgcrypt liblz4 lzo2 lzma bzip2 libxml2 libqb doxygen groff dbus gmake curl jq check py${pyver}-pexpect py${pyver}-pycurl py${pyver}-requests py${pyver}-boto3 py${pyver}-google-api-python-client libxslt glib docbook-xsl libltdl e2fsprogs-libuuid libxslt ncurses bison byacc flex help2man gnutls asciidoc getopt p5-Locale-gettext openipmi zstd py${pyver}-keystoneauth1 py${pyver}-python-keystoneclient py${pyver}-python-novaclient py${pyver}-suds cmocka gsnmp $rustdeps
pkg install -y net-snmp || true
pkg clean -a -y
pkg autoremove -y
getent group haclient >/dev/null || pw groupadd haclient
getent passwd hacluster >/dev/null || pw useradd hacluster -g haclient -s /nonexistent -c "cluster user"
