#!/bin/sh

set -ev

cd /root

$HOME/ci-tools/ci-update-common

JOBNAME=$(echo ${JOB_BASE_NAME}  | sed -e 's/=.*//g')

case ${JOBNAME} in
 *unstable)
  upgrade=dup
  ;;
 *stable)
  upgrade=update
  ;;
esac

zypper clean
zypper $upgrade -y
zypper install -y make git gcc clang automake libtool autoconf valgrind lksctp-tools-devel mozilla-nss-devel libopenssl-devel zlib-devel liblz4-devel lzo-devel xz-devel libbz2-devel libqb-devel libxml2-devel rpm-build doxygen groff-full dbus-1-devel net-snmp-devel systemd-devel curl jq check-devel time libxml2-tools libxslt-tools glib2-devel docbook-xsl-stylesheets libuuid-devel libxslt-devel pam-devel ncurses-devel bison byacc flex help2man libgnutls-devel inkscape asciidoc cluster-glue OpenIPMI-devel libnl3-devel libzstd-devel python-devel libaio-devel libglue-devel libnet-devel python3-keystoneclient python3-keystoneauth1 python3-novaclient libvirt-devel python3-pexpect python3-pycurl python3-suds-jurko python3-requests python3-openwsman python3-boto3 python3-google-api-python-client python3-systemd execstack python3-setuptools python3-devel ruby ruby-devel fontconfig liberation-fonts npm rpmdevtools gcc-c++ firewall-macros
getent group haclient >/dev/null || groupadd -r haclient -g 189
getent passwd hacluster >/dev/null || useradd -r -g haclient -u 189 -s /sbin/nologin -c "cluster user" hacluster
