#!/bin/sh

# ENTRY POINT (old / done)

set -e

$CITHOME/ci-update-common

case "${NODE_NAME}" in
 rhel*)
  wget --no-check-certificate -O /etc/pki/ca-trust/source/anchors/RH-IT-Root-CA.crt https://certs.corp.redhat.com/certs/Current-IT-Root-CAs.pem
  wget --no-check-certificate -O /etc/pki/ca-trust/source/anchors/Eng-CA.crt https://engineering.redhat.com/Eng-CA.crt
  update-ca-trust
 ;;
esac

yum clean all

case "${NODE_NAME}" in
 centos-*|anvil-ci-centos-*|anvil-ci-bm*)
  yum -y install epel-release
 ;;
 rhel8*|anvil-ci-rhel-8)
  if ! rpm -qa | grep epel-release; then
   yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
  fi
 ;;
 rhel9*|anvil-ci-rhel-9)
  if ! rpm -qa | grep epel-release; then
   yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
  fi
 ;;
esac

case "${NODE_NAME}" in
 anvil-ci-bm*)
  EXTRAOPTS="--exclude=neo4j --exclude=cypher-shell"
 ;;
esac

case "${NODE_NAME}" in
 *centos-9*)
  POSTOPTS="--nobest"
 ;;
esac

yum -y $EXTRAOPTS update $POSTOPTS

# handle special packages that are not available everywhere
for i in libcgroup-devel libservicelog-devel python3-google-api-client; do
 yum -y install $i || true
done

EXTRADEPS=""

case "${NODE_NAME}" in
 centos*|rhel*|anvil-ci-centos*|anvil-ci-rhel*)
  EXTRADEPS="platform-python-devel $EXTRADEPS"
 ;;
esac

case "${NODE_NAME}" in
 anvil-ci*)
  EXTRADEPS="fence-agents-common resource-agents mock wget rpm-build createrepo_c yum-utils $EXTRADEPS"
 ;;
esac

# rust bindings
if [ -n "$RUSTBINDINGS" ] && [ "$RUSTBINDINGS" = yes ]; then
  EXTRADEPS="bindgen clippy rustfmt $EXTRADEPS"
fi

# shellcheck for resource-agents ci/build.sh
case "${NODE_NAME}" in
 fedora*)
  EXTRADEPS="ShellCheck $EXTRADEPS"
 ;;
esac

# annobin-annocheck is off sync on rhel85 power
case "${NODE_NAME}" in
 *power*)
 ;;
 *)
  EXTRADEPS="annobin-annocheck $EXTRADEPS"
 ;;
esac

# rhel9 language pack
case "${NODE_NAME}" in
 rhel9*)
  EXTRADEPS="glibc-all-langpacks $EXTRADEPS"
 ;;
esac

yum -y install             \
 OpenIPMI-devel            \
 asciidoc                  \
 autoconf                  \
 automake                  \
 bison                     \
 byacc                     \
 bzip2-devel               \
 cargo                     \
 check-devel               \
 clang                     \
 curl                      \
 dbus-devel                \
 docbook-style-xsl         \
 doxygen                   \
 execstack                 \
 flex                      \
 fontconfig                \
 gcc                       \
 gettext-devel             \
 git                       \
 glib2-devel               \
 gnutls-devel              \
 groff                     \
 help2man                  \
 inkscape                  \
 jq                        \
 libaio-devel              \
 libblkid-devel            \
 libcmocka-devel           \
 libcurl-devel             \
 liberation-sans-fonts     \
 libffi-devel              \
 libgcrypt-devel           \
 libnet-devel              \
 libnl3-devel              \
 libqb-devel               \
 libtool                   \
 libtool-ltdl-devel        \
 libuuid-devel             \
 libvirt-devel             \
 libxml2-devel             \
 libxslt                   \
 libxslt-devel             \
 libzstd-devel             \
 lksctp-tools-devel        \
 lz4-devel                 \
 lzo-devel                 \
 make                      \
 net-snmp-devel            \
 ncurses-devel             \
 npm                       \
 nss-devel                 \
 nss-tools                 \
 openssl-devel             \
 openwsman-python3         \
 overpass-fonts            \
 pam-devel                 \
 perl                      \
 python3-boto3             \
 python3-cryptography      \
 python3-devel             \
 python3-httplib2          \
 python3-lxml              \
 python3-pexpect           \
 python3-pip               \
 python3-pycurl            \
 python3-pyroute2          \
 python3-requests          \
 python3-rpm-macros        \
 python3-setuptools        \
 python3-setuptools_scm    \
 python3-systemd           \
 python3-suds              \
 python3-wheel             \
 psmisc                    \
 rpm-build                 \
 rpmdevtools               \
 rpmlint                   \
 rsync                     \
 ruby                      \
 ruby-devel                \
 rubygems                  \
 rubygem-bundler           \
 rust                      \
 systemd-devel             \
 time                      \
 util-linux                \
 valgrind                  \
 which                     \
 xz-devel                  \
 zlib-devel                \
 $EXTRADEPS

case "${NODE_NAME}" in
 *kbuild*|*vapor*)
  yum -y update
  yum -y install python3-devel python3-pip python3-wheel \
		 brewkoji createrepo ansible \
		 azure-cli firewalld-filesystem jq \
		 google-cloud-sdk python3-openstackclient \
		 libcurl-devel libvirt-devel openssl-devel gcc \
		 tox crudini libxml2 \
		 nmap-ncat \
		 python3-vapor
 ;;
esac

getent group haclient >/dev/null || groupadd -r haclient -g 189
getent passwd hacluster >/dev/null || useradd -r -g haclient -u 189 -s /sbin/nologin -c "cluster user" hacluster
