#!/bin/sh

# ENTRY POINT (old / done)

set -e

$CITHOME/ci-update-common

export DEBIAN_FRONTEND=noninteractive

apt-get update --allow-releaseinfo-change || apt-get update
apt-get -y dist-upgrade
apt-get -y autoremove

# Required
apt-get -y install      \
 asciidoc               \
 autoconf               \
 autopoint              \
 autotools-dev          \
 bison                  \
 build-essential        \
 byacc                  \
 check                  \
 chrpath                \
 clang                  \
 cluster-glue-dev       \
 curl                   \
 docbook-xsl            \
 doxygen                \
 flex                   \
 gcc                    \
 gettext                \
 git                    \
 groff                  \
 help2man               \
 jq                     \
 libaio-dev             \
 libblkid-dev           \
 libbz2-dev             \
 libcgroup-dev          \
 libcmocka-dev          \
 libcurl4-openssl-dev   \
 libdbus-1-dev          \
 libgcrypt-dev          \
 libglib2.0-dev         \
 libgnutls28-dev        \
 libltdl-dev            \
 liblz4-dev             \
 liblzma-dev            \
 liblzo2-dev            \
 libncurses-dev         \
 libnl-3-dev            \
 libnl-route-3-dev      \
 libnss3-dev            \
 libnspr4-dev           \
 libnss3-tools          \
 libopenipmi-dev        \
 libpam0g-dev           \
 libqb-dev              \
 libsctp-dev            \
 libsnmp-dev            \
 libssl-dev             \
 libsystemd-dev         \
 libtool                \
 libtool-bin            \
 libvirt-dev            \
 libxml2-dev            \
 libxml2-utils          \
 libxslt1-dev           \
 libzstd-dev            \
 make                   \
 perl                   \
 pkg-config             \
 psmisc                 \
 puma                   \
 python3-boto3          \
 python3-dev            \
 python3-googleapi      \
 python3-lxml           \
 python3-pexpect        \
 python3-pip            \
 python3-psutil         \
 python3-pyagentx       \
 python3-pycurl         \
 python3-pyparsing      \
 python3-requests       \
 python3-tornado        \
 python3-setuptools     \
 python3-setuptools-scm \
 python3-suds           \
 python3-systemd        \
 python3-venv           \
 rsync                  \
 ruby                   \
 ruby-backports         \
 ruby-bundler           \
 ruby-childprocess      \
 ruby-daemons           \
 ruby-dev               \
 ruby-ethon             \
 ruby-eventmachine      \
 ruby-ffi               \
 ruby-json              \
 ruby-mustermann        \
 ruby-open4             \
 ruby-rack              \
 ruby-rack-protection   \
 ruby-rack-test         \
 ruby-ruby2-keywords    \
 ruby-sinatra           \
 ruby-test-unit         \
 shellcheck             \
 time                   \
 uuid-dev               \
 uuid-runtime           \
 xsltproc               \
 zlib1g-dev

# Optional
apt-get -y install      \
 inkscape               \
 llvm                   \
 python3-dacite         \
 python3-distro         \
 ruby-rack-session      \
 ruby-rackup            \
 valgrind               \
 || true

if [ -n "$EXTRA_ARCH" ]; then
 dpkg --add-architecture $EXTRA_ARCH
 apt-get update
 apt-get -y install                \
  crossbuild-essential-$EXTRA_ARCH \
  libbz2-dev:$EXTRA_ARCH           \
  libgcrypt-dev:$EXTRA_ARCH        \
  liblz4-dev:$EXTRA_ARCH           \
  liblzma-dev:$EXTRA_ARCH          \
  liblzo2-dev:$EXTRA_ARCH          \
  libnspr4-dev:$EXTRA_ARCH         \
  libnl-3-dev:$EXTRA_ARCH          \
  libnl-route-3-dev:$EXTRA_ARCH    \
  libnss3-dev:$EXTRA_ARCH          \
  libssl-dev:$EXTRA_ARCH           \
  libsctp-dev:$EXTRA_ARCH          \
  libzstd-dev:$EXTRA_ARCH          \
  pkg-config:$EXTRA_ARCH           \
  pkgconf:$EXTRA_ARCH              \
  zlib1g-dev:$EXTRA_ARCH
fi
apt-get -y clean
getent group haclient >/dev/null || addgroup --system haclient
getent passwd hacluster >/dev/null || adduser --system --ingroup haclient --gecos "cluster user" --no-create-home hacluster
