#!/bin/sh

set -e

rm -rf $HOME/rpmbuild
rm -rf /usr/src/packages/BUILDROOT/*
# the test job can only clean up to a certain point
# this is more likely to avoid qb leaks
rm -rf /dev/shm/qb*
rm -rf /dev/shm/testvol*
rm -rf /tmp/libqb*
rm -rf /tmp/booth-tests*

$CITHOME/ci-generate-start-node
