#!/bin/sh

set -ev

cd /root

$HOME/ci-tools/ci-update-common

JOBNAME=$(echo ${JOB_BASE_NAME}  | sed -e 's/=.*//g')

case ${JOBNAME} in
 *unstable)
  upgrade=dup
  ;;
 *stable)
  upgrade=update
  bundler=ruby2.5-rubygem-bundler
  ;;
esac

zypper clean
zypper $upgrade -y
zypper install -y $bundler        \
 OpenIPMI-devel                   \
 asciidoc                         \
 autoconf                         \
 automake                         \
 bison                            \
 byacc                            \
 check-devel                      \
 clang                            \
 cluster-glue                     \
 curl                             \
 dbus-1-devel                     \
 docbook-xsl-stylesheets          \
 doxygen                          \
 execstack                        \
 firewall-macros                  \
 flex                             \
 fontconfig                       \
 gcc                              \
 gcc-c++                          \
 gettext-tools                    \
 git                              \
 glib2-devel                      \
 groff-full                       \
 help2man                         \
 inkscape                         \
 jq                               \
 libaio-devel                     \
 libbz2-devel                     \
 libcmocka-devel                  \
 libcurl-devel                    \
 liberation-fonts                 \
 libgcrypt-devel                  \
 libglue-devel                    \
 libgnutls-devel                  \
 liblz4-devel                     \
 libnet-devel                     \
 libnl3-devel                     \
 libopenssl-devel                 \
 libqb-devel                      \
 libtool                          \
 libuuid-devel                    \
 libvirt-devel                    \
 libxml2-devel                    \
 libxml2-tools                    \
 libxslt-devel                    \
 libxslt-tools                    \
 libzstd-devel                    \
 lksctp-tools-devel               \
 lzo-devel                        \
 make                             \
 mozilla-nss-devel                \
 ncurses-devel                    \
 net-snmp-devel                   \
 npm                              \
 pam-devel                        \
 python3-boto3                    \
 python3-devel                    \
 python3-google-api-python-client \
 python3-keystoneauth1            \
 python3-keystoneclient           \
 python3-lxml                     \
 python3-novaclient               \
 python3-openwsman                \
 python3-pexpect                  \
 python3-pycurl                   \
 python3-requests                 \
 python3-setuptools               \
 python3-setuptools_scm           \
 python3-suds-jurko               \
 python3-systemd                  \
 python3-wheel                    \
 python-devel                     \
 rpm-build                        \
 rpmdevtools                      \
 rpmlint                          \
 rsync                            \
 ruby                             \
 ruby-devel                       \
 systemd-devel                    \
 time                             \
 valgrind                         \
 xz-devel                         \
 zlib-devel
getent group haclient >/dev/null || groupadd -r haclient -g 189
getent passwd hacluster >/dev/null || useradd -r -g haclient -u 189 -s /sbin/nologin -c "cluster user" hacluster
