#!/bin/sh

cijava=`find /usr/lib/jvm -mindepth 1 -maxdepth 1 -type d -name "*openjdk*" | sort -V | tail -n 1`/bin/java

$cijava \
	-jar $HOME/ci-tools/jenkins-cli.jar \
	-auth @$HOME/token \
	-s http://localhost:8080/ \
	"$@"
