#!/bin/bash

set -e

trap cleanup EXIT

cleanup() {
	[ -n "$TMPDIR" ] && rm -rf $TMPDIR
}

TMPDIR=$(mktemp -d /tmp/jnodemgmtXXXXXX)

getnodelist() {
	nodelist="$(ls -1 $HOME/nodes)"
}

getjoblist() {
	cd $HOME/jobs
	joblist="$(ls -1 */config.xml */*/config.xml */*/*/config.xml 2>/dev/null | sed -e 's#/config.xml##g' || true)"
	cd $HOME
}

delnodefromjob() {
	job="$1"
	node="$2"

	cp $HOME/jobs/$job/config.xml $TMPDIR/${node}.xml

	xmlstarlet ed \
		--net \
		--inplace \
		--delete "/matrix-project/axes/hudson.matrix.LabelAxis/values/string[contains(text(),'$node')]" \
		$TMPDIR/${node}.xml 2>/dev/null

	cat $TMPDIR/${node}.xml > $HOME/jobs/$job/config.xml

	rm -rf $TMPDIR/${node}.xml
}

delnodefromalljobs() {
	node="$1"
	for i in $nodejobs; do
		delnodefromjob $i $node
	done
}

addnodetojob() {
	job="$1"
	node="$2"

	cp $HOME/jobs/$job/config.xml $TMPDIR/${node}.xml

	xmlstarlet ed \
		--net \
		--inplace \
		--insert "/matrix-project/axes/hudson.matrix.LabelAxis/values/string[1]" \
		--type elem \
		--name string \
		--value $node \
		$TMPDIR/${node}.xml 2>/dev/null

	cat $TMPDIR/${node}.xml > $HOME/jobs/$job/config.xml

	rm -rf $TMPDIR/${node}.xml
}

addnodetoalljobs() {
	node="$1"
	rpm=no
	clang=yes
	packager=""
	voting=no
	oldbuilds=no

	labels=$(cat $HOME/ci-tools/pipelines/libs/global/vars/getNodes.groovy | grep $node | sed -e 's#.*\[##g' -e "s#'##g" -e 's#]##g' -e 's#,# #g')

	echo $labels

	for i in $labels; do
		case $i in
			rpm)
				rpm=yes
				;;
			noclang)
				clang=no
				;;
			yum|zypper|apt|freebsd)
				packager=$i
				;;
			voting)
				voting=yes
				;;
			stable|unstable)
				updater=$i
				;;
			rhel8*|centos-8*)
				oldbuilds=yes
				;;
		esac
	done
	echo rpm $rpm clang $clang packager $packager voting $voting
	echo $joblist
	localjoblist=""
	for i in $joblist; do
		addjob=0
		case $i in
			*anvil*|*pagure-hook*|*ci-test*|*pipeline*)
				echo Skipping manual job $i
				;;
			*all-weekly|*build-rpm-repos|*reinstall-all-manual|*reconnect-all-nodes|*get-artifacts|*folder-template)
				echo Skipping global job $i
				;;
			*after-merge|*github-pr-builder|*covscan*|*crosscompile*)
				echo Skipping hook job $i
				;;
			*ha-functional*)
				echo Skipping functional job $i
				;;
			*update-all-ci-tools)
				echo Adding updating job $i
				addjob=1
				;;
			*update-all-${packager}-${updater})
				echo Adding updating job $i
				addjob=1
				;;
			*update-anvil*|*update-all*|*update-freebsd-devel|*update-kernel-devel)
				echo Skipping updating job $i
				;;
			*clang)
				if [ $clang == yes ]; then
					echo Adding to clang job $i
					addjob=1
				else
					echo Skipping clang job $i
				fi
				;;
			*pcs*)
				case $i in
					*pcs-0*)
						# managed manually
						;;
					*rpms)
						if [ $rpm == yes ]; then
							if [ $oldbuilds == yes ]; then
								echo Skipping oldbuilds job $i
							else
								echo Adding oldbuilds to job $i
								addjob=1
							fi
						fi
						;;
					*-nonvoting)
						if [ $voting == no ]; then
							if [ $oldbuilds == yes ]; then
								echo Skipping oldbuilds job $i
							else
								echo Adding oldbuilds to job $i
								addjob=1
							fi
						else
							echo Skipping nonvoting job $i
						fi
						;;
					*-voting)
						if [ $voting == yes ]; then
							if [ $oldbuilds == yes ]; then
								echo Skipping oldbuilds job $i
							else
								echo Adding oldbuilds to job $i
								addjob=1
							fi
						else
							echo Skipping voting job $i
						fi
						;;
					*)
						if [ $oldbuilds == yes ]; then
							echo Skipping oldbuilds job $i
						else
							echo Adding oldbuilds to job $i
							addjob=1
						fi
						;;
				esac
				;;
			*rpms)
				case $i in
					*pcs*)
						echo Skipping rpm job $i - managed separately
					;;
					*)
						if [ $rpm == yes ]; then
							echo Adding to rpm job $i
							addjob=1
						else
							echo Skipping rpm job $i
						fi
					;;
				esac
				;;
			*-nonvoting)
				if [ $voting == no ]; then
					echo Adding to nonvoting job $i
					addjob=1
				else
					echo Skipping nonvoting job $i
				fi
				;;
			*-voting)
				if [ $voting == yes ]; then
					echo Adding to voting job $i
					addjob=1
				else
					echo Skipping voting job $i
				fi
				;;
			*)
				echo Adding leftover $i
				addjob=1
				;;
		esac
		if [ $addjob == 1 ]; then
			localjoblist="$localjoblist $i"
		fi
	done
	echo $localjoblist
	for i in $localjoblist; do
		addnodetojob $i $node
	done
}

listnodejobs()
{
	node="$1"

	for job in $joblist; do
		grep -l $node $HOME/jobs/$job/config.xml | sed \
			-e 's#/config.xml##g' \
			-e 's#'$HOME'/jobs/##g'
	done
}

action=$1
node=$2

getjoblist
getnodelist
nodejobs="$(listnodejobs $node)"

reloadconfig=1

case $action in
	del)
		delnodefromalljobs $node
	;;
	add)
		addnodetoalljobs $node
	;;
	list)
		echo "$nodejobs"
		reloadconfig=0
	;;
	add-to-job-list)
		shift
		shift
		jobs=$@
		for job in $jobs; do
			addnodetojob $job $node
		done
	;;
	*)
		echo "No action specified. Do nothing"
		exit 0
	;;
esac

if [ "$reloadconfig" = "1" ]; then
	./jcli reload-configuration 2>/dev/null
fi

exit 0
