// Jenkinsfile for building anvil kmods

@Library(['GlobalLib', 'ProjectLib']) _

// Globals
def project = 'anvil'
def info = ['project': project, 'branch': "kmod $BASEDISTRO $REPOSRC $ANVILSRC"]

pipeline {
    agent { label 'anvil-bm' }

    options {
	skipDefaultCheckout(true)
    }

    stages {
	// First check we are allowed to run, then set some params for that run
	stage('Prep build env') {
	    steps {
		cleanWs(disableDeferredWipeout: true, deleteDirs: true)
		getBuildInfoCommon(info)
		sh """
		    /root/ci-tools/ci-destroy-anvil-bm-vm
		"""
	    }
	}
	stage('Build kmod') {
	    steps {
		sh """
		    /root/ci-tools/ci-setup-anvil-bm-vm-kmods $BASEDISTRO $REPOSRC $ANVILSRC
		"""
	    }
	}
    }
    post {
	success {
	    script {
		info['state'] = 'success'
		projectFinishUp(info)
	    }
	}
	failure {
	    script {
		info['state'] = 'failure'
		projectFinishUp(info)
	    }
	}
	always {
	    sh """
		/root/ci-tools/ci-destroy-anvil-bm-vm
	    """
	    cleanWs(disableDeferredWipeout: true, deleteDirs: true)
	}
    }
}
