@Library(['GlobalLib@fab-devel', 'ProjectLib@fab-devel']) _

def info = [:]
def project = 'kubesan-cache'
def execnodes = getLabelledNodes('kubesan')

pipeline {
    agent { label 'kubesan-cache' }

    options {
	skipDefaultCheckout(true)
    }

    stages {
	stage('Clean build env') {
	    steps {
		script {
		    getBuildInfoCommon(info)
		}
	    }
	}
	stage('Build kubesan registry cache') {
	    steps {
		script {
		    withCredentials([usernamePassword(credentialsId: 'kubesan-docker', passwordVariable: 'docker_password', usernameVariable: 'docker_user')]) {
			sh "echo $HOME/ci-tools/ci-wrap ci-kubesan-cache"
		    }
		}
		println("execnodes: "+execnodes)
	    }
	}
    }
    post {
	always {
	    cleanWs(disableDeferredWipeout: true, deleteDirs: true)
	}
    }
}
