#!/bin/sh

# ENTRY POINT (old)

set -e

rm -f /root/.pre_upgrade_done
cd /usr/src
git pull
make -j $(nproc) buildworld
make -j $(nproc) buildkernel KERNCONF=GENERIC-NODEBUG
touch /root/.pre_upgrade_done
