// Jenkinsfile for the corosync project

@Library(['GlobalLib@fab-devel', 'GithubLib', 'ProjectLib']) _

// Who we are
def project = 'corosync'
def info = [:]

// Pipeline code starts here
pipeline {
    // Start on the main Jenkins node. Build jobs are distributed inside 'parallel' below
    agent { label 'built-in' }

    // Things that external jobs might want to influence
    parameters {
	string(name: 'bootstrap',   defaultValue: '0', description: 'Bootstrap the RPM repos')
	string(name: 'fullrebuild', defaultValue: '0', description: 'This is a full rebuild - do not publish RPM and do NOT update build code on the nodes')
    }

    stages {
	// First check we are allowed to run, then set some params for that run
	stage('Setup build env') {
	    steps {
		script {
		    getBuildInfo(project, info)
		}
	    }
	}

        // This is the main stage - building and testing
	stage('Main stage') {
	    when {
		// getAuthCheck (in getBuildInfo) will usually abort the job if permission is denied,
		// but this is an extra check.
		expression { info['authcheck'] == true && info['is_draft'] == false }
	    }

	    // All of the stages that actually do stuff
	    steps {
		script {
		    cleanWs(disableDeferredWipeout: true, deleteDirs: true)

		    voting_kmain = buildRunMap('kmain-voting', info, ['voting': true,
								      'nodelabel': 'voting',
								      'extravars': ['depbuildname': 'kronosnet',
										    'depbuildversion': 'main',
										    'install': info['maininstall']]])
		    voting_kstable = buildRunMap('kstable-voting', info, ['voting': true,
									  'nodelabel': 'voting',
									  'extravars': ['depbuildname': 'kronosnet',
											'depbuildversion': 'stable1-proposed',
											'install': info['stableinstall']]])

		    nonvoting_kmain = buildRunMap('kmain-nonvoting', info, ['voting': false,
									    'nodelabel': 'nonvoting',
									    'extravars': ['depbuildname': 'kronosnet',
											  'depbuildversion': 'main',
											  'install': info['maininstall']]])
		    nonvoting_kstable = buildRunMap('kstable-nonvoting', info, ['voting': false,
										'nodelabel': 'nonvoting',
										'extravars': ['depbuildname': 'kronosnet',
											      'depbuildversion': 'stable1-proposed',
											      'install': info['stableinstall']]])

		    nonvoting_clang_kmain = buildRunMap('kmain-nonvoting-clang', info, ['voting': false,
											'nodelabel': 'nonvoting-clang',
											'extravars': ['compiler': 'clang',
												      'depbuildname': 'kronosnet',
												      'depbuildversion': 'main',
												      'install': 0]])
		    nonvoting_clang_kstable = buildRunMap('kstable-nonvoting-clang', info, ['voting': false,
											    'nodelabel': 'nonvoting-clang',
											    'extravars': ['compiler': 'clang',
													  'depbuildname': 'kronosnet',
													  'depbuildversion': 'stable1-proposed',
													  'install': 0]])

		    covscan_kmain = buildRunMap('kmain-covscan', info, ['voting': true,
									'nodelabel': 'covscan',
									'extravars': ['depbuildname': 'kronosnet',
										      'depbuildversion': 'main']])
		    covscan_kstable = buildRunMap('kstable-covscan', info, ['voting': true,
									    'nodelabel': 'covscan',
									    'extravars': ['depbuildname': 'kronosnet',
											  'depbuildversion': 'stable1-proposed']])

		    buildrpms_kmain = buildRunMap('kmain-buildrpms', info, ['voting': true,
									    'nodelabel': 'buildrpms',
									    'extravars': ['depbuildname': 'kronosnet',
											  'depbuildversion': 'main',
											  'publishrpm': info['maininstall']]])
		    buildrpms_kstable = buildRunMap('kstable-buildrpms', info, ['voting': true,
										'nodelabel': 'buildrpms',
										'extravars': ['depbuildname': 'kronosnet',
											      'depbuildversion': 'stable1-proposed',
											      'publishrpm': info['stableinstall']]])

		    // Run them (errors are caught in info[:])
		    try {
			parallel voting_kmain + voting_kstable +
			    nonvoting_kmain + nonvoting_kstable +
			    nonvoting_clang_kmain + nonvoting_clang_kstable +
			    buildrpms_kmain + buildrpms_kstable +
			    covscan_kmain + covscan_kstable
		    } catch (err) {
			println("Jenkinsfile caught "+err)
			info['exception_text'] += "\nparallel error caught: {$err}\n"
		    }
		}
	    }
	}

        // Build the RPM/Coverity repos etc. If the job failed, this is what tells Jenkins
	stage('Post Stage') {
	    when {
		expression { info['authcheck'] == true && info['is_draft'] == false }
	    }
	    steps {
		postStage(info)
	    }
	}
    }

    // Finish up and send emails
    post {
	always {
	    projectFinishUp(info)
	}
    }
}
