// Jenkinsfile for corosync CI project

@Library(['GlobalLib', 'ProjectLib']) _

// Globals
def project = 'corosync'

def authcheck = false

// github specific
def isPullRequest = env.CHANGE_ID ? true : false

// Set defaults
def nonvoting_fail = 0
def voting_fail = 0
def target_branch = ''
def target = ''
def pull_id = '1'
def actual_commit = ''
def install = 0
def maininstall = 0
def stableinstall = 0
def publish_pr_rpm = 0
def covopts = ''
def is_draft = false

pipeline {
    agent { label 'built-in' }

    stages {
	// First check we are allowed to run
	stage('Validate build env') {
	    steps {
		script {
		    cred_uuid = getCredUUID()
		    withCredentials([gitUsernamePassword(credentialsId: cred_uuid, gitToolName: 'Default')]) {
			authcheck = getGithubAuthCheck(['isPullRequest': isPullRequest])
		    }
		    // set parameters the sub-jobs.
		    if (isPullRequest) {
			target_branch = env.CHANGE_TARGET
			target = env.CHANGE_TARGET
			pull_id = env.CHANGE_ID
			actual_commit = env.GIT_COMMIT
			install = 0
			maininstall = 0
			stableinstall = 0
			publish_pr_rpm = buildPRRPMs(['isPullRequest': isPullRequest, 'branch': target])

			// Check for PRs marked 'draft' - this is Github-specific
			is_draft = pullRequest.isDraft()
			if (is_draft) {
			    // Default for most HA jobs - abort
			    currentBuild.result = 'ABORTED'
			    error('PR is marked as draft - pipeline will not run')
			}

			// For special jobs (manual override)
//			if (is_draft) {
//                            set_some_variables_for_build_or_something
//                            is_draft = false
//			}
		    } else {
			actual_commit = "origin/${env.BRANCH_NAME}"
			target = env.BRANCH_NAME
			install = isThisAnInstallBranch(target)
			if ("${install}" == '1') {
			    if ("${target}" == 'main') {
				maininstall = 1
				stableinstall = 0
			    } else {
				maininstall = 0
				stableinstall = 1
			    }
			}
		    }
		    covopts = getCovOpts(target)
		}
	    }
	}

	// This is the main stage that covers everything
	stage('Start builds') {
	    when {
		// getAuthCheck will usually abort the job if permission is denied
		// but this is an extra check!
		expression { authcheck == true && is_draft == false }
	    }
	    // All of the stages that actually do stuff
	    stages {
		stage('Standard builds') {
		    parallel {
			stage('voting vs kronosnet main') {
			    steps {
				build job: "${project}-build-all-voting",
				    parameters: [string(name: 'install', value: "${maininstall}"),
						 string(name: 'ghprbActualCommit', value : "${actual_commit}"),
						 string(name: 'ghprbPullId', value : "${pull_id}"),
						 string(name: 'ghprbTargetBranch', value : "${target_branch}"),
						 string(name: 'knetver', value : 'main'),
						 string(name: 'compiler', value : 'gcc')]
			    }
			}
			stage('voting vs kronosnet stable1-proposed') {
			    steps {
				build job: "${project}-build-all-voting",
				    parameters: [string(name: 'install', value: "${stableinstall}"),
						 string(name: 'ghprbActualCommit', value : "${actual_commit}"),
						 string(name: 'ghprbPullId', value : "${pull_id}"),
						 string(name: 'ghprbTargetBranch', value : "${target_branch}"),
						 string(name: 'knetver', value : 'stable1-proposed'),
						 string(name: 'compiler', value : 'gcc')]
			    }
			}
			stage('covscan vs kronosnet main') {
			    steps {
				// covscan always install on merge
				build job: "${project}-build-covscan",
				    parameters: [string(name: 'install', value: "${install}"),
						 string(name: 'ghprbActualCommit', value : "${actual_commit}"),
						 string(name: 'ghprbPullId', value : "${pull_id}"),
						 string(name: 'ghprbTargetBranch', value : "${target_branch}"),
						 string(name: 'knetver', value : 'main'),
						 string(name: 'covoptions', value : "${covopts}")]
			    }
			}
			stage('covscan vs kronosnet stable1-proposed') {
			    steps {
				// covscan always install on merge
				build job: "${project}-build-covscan",
				    parameters: [string(name: 'install', value: "${install}"),
						 string(name: 'ghprbActualCommit', value : "${actual_commit}"),
						 string(name: 'ghprbPullId', value : "${pull_id}"),
						 string(name: 'ghprbTargetBranch', value : "${target_branch}"),
						 string(name: 'knetver', value : 'stable1-proposed'),
						 string(name: 'covoptions', value : "${covopts}")]
			    }
			}
			stage('rpm builds vs kronosnet main') {
			    steps {
				build job: "${project}-build-rpms",
				    parameters: [string(name: 'ghprbActualCommit', value : "${actual_commit}"),
						 string(name: 'ghprbPullId', value : "${pull_id}"),
						 string(name: 'ghprbTargetBranch', value : "${target_branch}"),
						 string(name: 'publishrpm', value : "${maininstall}"),
						 string(name: 'publishprrpm', value : "${publish_pr_rpm}"),
						 string(name: 'knetver', value : 'main'),
						 string(name: 'bootstrap', value : '0')]
			    }
			}
			stage('rpm builds vs kronosnet stable1-proposed') {
			    steps {
				build job: "${project}-build-rpms",
				    parameters: [string(name: 'ghprbActualCommit', value : "${actual_commit}"),
						 string(name: 'ghprbPullId', value : "${pull_id}"),
						 string(name: 'ghprbTargetBranch', value : "${target_branch}"),
						 string(name: 'publishrpm', value : "${stableinstall}"),
						 string(name: 'publishprrpm', value : "${publish_pr_rpm}"),
						 string(name: 'knetver', value : 'stable1-proposed'),
						 string(name: 'bootstrap', value : '0')]
			    }
			}
			stage('non-voting vs kronosnet main') {
			    steps {
				script {
				    try {
					build job: "${project}-build-all-nonvoting",
					    parameters: [string(name: 'install', value: "${maininstall}"),
							 string(name: 'ghprbActualCommit', value : "${actual_commit}"),
							 string(name: 'ghprbPullId', value : "${pull_id}"),
							 string(name: 'ghprbTargetBranch', value : "${target_branch}"),
							 string(name: 'knetver', value : 'main'),
							 string(name: 'compiler', value : 'gcc')]
				    }
				    catch (err) {
					nonvoting_fail++
				    }
				}
			    }
			}
			stage('non-voting vs kronosnet stable1-proposed') {
			    steps {
				script {
				    try {
					build job: "${project}-build-all-nonvoting",
					    parameters: [string(name: 'install', value: "${stableinstall}"),
							 string(name: 'ghprbActualCommit', value : "${actual_commit}"),
							 string(name: 'ghprbPullId', value : "${pull_id}"),
							 string(name: 'ghprbTargetBranch', value : "${target_branch}"),
							 string(name: 'knetver', value : 'stable1-proposed'),
							 string(name: 'compiler', value : 'gcc')]
				    }
				    catch (err) {
					nonvoting_fail++
				    }
				}
			    }
			}
			stage('non-voting-clang vs kronosnet main') {
			    steps {
				script {
				    try {
					build job: "${project}-build-all-nonvoting-clang",
					    parameters: [string(name: 'ghprbActualCommit', value : "${actual_commit}"),
							 string(name: 'ghprbPullId', value : "${pull_id}"),
							 string(name: 'ghprbTargetBranch', value : "${target_branch}"),
							 string(name: 'knetver', value : 'main')]
				    }
				    catch (err) {
					nonvoting_fail++
				    }
				}
			    }
			}
			stage('non-voting-clang vs kronosnet stable1-proposed') {
			    steps {
				script {
				    try {
					build job: "${project}-build-all-nonvoting-clang",
					    parameters: [string(name: 'ghprbActualCommit', value : "${actual_commit}"),
							 string(name: 'ghprbPullId', value : "${pull_id}"),
							 string(name: 'ghprbTargetBranch', value : "${target_branch}"),
							 string(name: 'knetver', value : 'stable1-proposed')]
				    }
				    catch (err) {
					nonvoting_fail++
				    }
				}
			    }
			}
		    }
		}
	    }
	}
    }
    post {
	success {
	    // Notify interested users if non-voting jobs fail
	    script {
		postFunctions(['project': project, 'state': 'success', 'nonvoting_fail': nonvoting_fail, 'voting_fail': voting_fail])
	    }
	}
	failure {
	    // Notify interested users if voting jobs fail
	    script {
		postFunctions(['project': project, 'state': 'failure', 'nonvoting_fail': nonvoting_fail, 'voting_fail': voting_fail])
	    }
	}
    }
}
