// Jenkinsfile for the pcs-functiona-testing

@Library(['GlobalLib', 'VaporLib@fab-devel', 'ProjectLib']) _

def project = 'pcs-functional-testing'
def projectid = 'pcs'
def info = [:]

// pcs overrides
def provider = 'osp'
def testvariant = 'pcs'

pipeline {
    agent { label "${provider}" }

    options {
	skipDefaultCheckout(true)
    }

    stages {
	stage('Prepare test cluster') {
	    steps {
		script {
		    getBuildInfo(project, projectid, info)
		    // apply pcs overrides
		    info['provider'] = provider
		    info['testvariant' ] = testvariant
		    // prep default test cluster
		    prep_test_cluster(info)
		}
	    }
	}
	stage('Run tests') {
	    steps {
		script {
		    run_functional_tests(info)
		}
	    }
	}
    }

    post {
	always {
	    post_functional_tests(info)
	}
    }
}
