// Update anvil external dependencies repos

@Library(['GlobalLib', 'GithubLib', 'ProjectLib']) _

def info = [:]
def project = 'anvil-build-dep-repos'

// Generate the run-list
def buildFullRunMap(Map info)
{
    def collectBuildEnv = [:]
    def nodeList = getLabelledNodes('anvil')
    def downnodes = getLabelledNodes('down')
    println('"Down" nodes: '+downnodes)

    for (n in nodeList) {
	def node = n
	if (!downnodes.contains(node)) {
	    collectBuildEnv[node] = {
		anvil_build_dep_repos(node, info)
	    }
	}
    }

    return collectBuildEnv
}

pipeline {
    agent { label 'built-in' }

    stages {
	stage('Setup build env') {
            steps {
		script {
		    getBuildInfo(project, info)
		    info['state'] = 'success'
		    info['branch'] = ''
		    info['stages_run'] = 0
		    info['stages_fail'] = 0
		    info['stages_fail_nodes'] = ''
		    info['email_extra_text'] = ''
		}
	    }
	}
        stage('build external deps repos') {
            steps {
		script {
		    // Now do all of the other nodes
		    def updates = buildFullRunMap(info)
		    try {
			parallel updates
			info['state'] = 'completed'
		    } catch (err) {
			println("Jenkinsfile caught "+err)
			info['exception_text'] += "\nparallel error caught: {$err}\n"
			info['state'] = 'error'
		    }
		}
	    }
        }
    }

    // Finish up and send emails
    post {
	always {
	    projectFinishUp(info)
	}
    }
}
