---
required_packages:
  - alpine-sdk
  - asciidoc
  - autoconf
  - automake
  - bison
  - check
  - check-dev
  - chrpath
  - clang
  - clang-libclang
  - cmocka
  - cmocka-dev
  - coreutils
  - curl
  - curl-dev
  - dbus-dev
  - docbook-xsl
  - doxygen
  - flex
  - flock
  - gcc
  - gettext
  - git
  - glib-dev
  - gnutls-dev
  - groff
  - help2man
  - jq
  - libaio-dev
  - libblkid
  - libbz2
  - libcgroup-dev
  - libgcrypt-dev
  - libltdl
  - libltdl-static
  - libnl3-dev
  - libqb-dev
  - libssl3
  - libtool
  - libvirt-dev
  - libxml2-dev
  - libxml2-utils
  - libxslt-dev
  - linux-pam-dev
  - lksctp-tools-dev
  - lz4-dev
  - lzo-dev
  - make
  - ncurses-dev
  - net-snmp-dev
  - nspr-dev
  - nss-dev
  - nss-tools
  - openipmi-dev
  - openrc-dev
  - openssl-dev
  - perl
  - pkgconf
  - psmisc
  - py3-boto3
  - py3-dateutil
  - py3-cryptography
  - python3-dev
  - py3-google-api-python-client
  - py3-lxml
  - py3-pexpect
  - py3-pip
  - py3-psutil
  - py3-curl
  - py3-parsing
  - py3-requests
  - py3-setuptools
  - py3-setuptools_scm
  - py3-suds-jurko
  - py3-tornado
  - py3-wheel
  - rsync
  - ruby
  - ruby-bundler
  - ruby-dev
  - ruby-eventmachine
  - ruby-ffi
  - ruby-json-schema
  - ruby-test-unit
  - sed
  - shellcheck
  - sudo
  - tar
  - time
  - util-linux-dev
  - uuidgen
  - wireshark-dev
  - xz-dev
  - zlib-dev
  - zstd-dev

optional_packages:
  - inkscape
  - llvm
  - py3-dacite
  - py3-distro
  - valgrind

rust_bindings:
  - rust
  - rust-bindgen
  - rust-clippy
  - rustfmt
