---
required_packages:
  - autoconf
  - automake
  - check
  - developer/clang-20
  - doxygen
  - gcc-14
  - gnu-binutils
  - gnu-coreutils
  - gnu-make
  - header-tun
  - icu
  - libtool
  - system/mozilla-nss
  - system/library/mozilla-nss
  - system/library/mozilla-nss/header-nss
  - tun
  - wireshark

boot_environments_to_keep: 4
boot_environments_cleanup_script: /root/bin/cleanup-boot-envs
