// Jenkinsfile for pcs CI project

@Library(['GlobalLib', 'GithubLib', 'ProjectLib']) _

// Globals
def project = 'pcs'
def draft_override = '0'
def nonvoting_fail = 0
def voting_fail = 0

pipeline {
    agent { label 'built-in' }

    stages {
	// First check we are allowed to run and collect generic job info
	stage('Validate build env') {
	    steps {
		script {
		    info = getBuildInfo(project, draft_override)
		}
	    }
	}

	// This is the main stage that covers everything for branch pcs-0.10
	stage('Start builds pcs-0.10 branch') {
	    when {
		// getAuthCheck will usually abort the job if permission is denied
		// but this is an extra check!
		expression { info['authcheck'] == true && info['target'] == 'pcs-0.10' && info['is_draft'] == false }
	    }
	    // All of the stages that actually do stuff
	    stages {
		stage('Standard builds') {
		    parallel {
			stage('voting vs pacemaker 2.1') {
			    steps {
				build job: "${project}-0.10-build-all-voting",
				    parameters: [string(name: 'ghprbActualCommit', value: "${info['actual_commit']}"),
						 string(name: 'ghprbPullId', value: "${info['pull_id']}"),
						 string(name: 'ghprbTargetBranch', value: "${info['target_branch']}"),
						 string(name: 'pcmkver', value: '2.1')]
			    }
			}
			stage('rpm builds') {
			    steps {
				build job: "${project}-0.10-build-rpms",
				    parameters: [string(name: 'ghprbActualCommit', value: "${info['actual_commit']}"),
						 string(name: 'ghprbPullId', value: "${info['pull_id']}"),
						 string(name: 'ghprbTargetBranch', value: "${info['target_branch']}"),
						 string(name: 'publishrpm', value: "${info['install']}"),
						 string(name: 'publishprrpm', value: "${info['publish_pr_rpm']}"),
						 string(name: 'bootstrap', value: '0')]
			    }
			}
		    }
		}
	    }
	}

	// This is the main stage that covers everything for branch main
	stage('Start builds main branch') {
	    when {
		// getAuthCheck will usually abort the job if permission is denied
		// but this is an extra check!
		expression { info['authcheck'] == true && info['target'] == 'main' && info['is_draft'] == false }
	    }
	    // All of the stages that actually do stuff
	    stages {
		stage('Standard builds') {
		    parallel {
			stage('voting vs pacemaker main') {
			    steps {
				build job: "${project}-build-all-voting",
				    parameters: [string(name: 'ghprbActualCommit', value: "${info['actual_commit']}"),
						 string(name: 'ghprbPullId', value: "${info['pull_id']}"),
						 string(name: 'ghprbTargetBranch', value: "${info['target_branch']}"),
						 string(name: 'pcmkver', value: 'main')]
			    }
			}
			stage('voting vs pacemaker 2.1') {
			    steps {
				build job: "${project}-build-all-voting",
				    parameters: [string(name: 'ghprbActualCommit', value: "${info['actual_commit']}"),
						 string(name: 'ghprbPullId', value: "${info['pull_id']}"),
						 string(name: 'ghprbTargetBranch', value: "${info['target_branch']}"),
						 string(name: 'pcmkver', value: '2.1')]
			    }
			}
			stage('covscan vs pacemaker main') {
			    steps {
				build job: "${project}-build-covscan",
				    parameters: [string(name: 'install', value: "${info['install']}"),
						 string(name: 'ghprbActualCommit', value: "${info['actual_commit']}"),
						 string(name: 'ghprbPullId', value: "${info['pull_id']}"),
						 string(name: 'ghprbTargetBranch', value: "${info['target_branch']}"),
						 string(name: 'pcmkver', value: 'main'),
						 string(name: 'covoptions', value: "${info['covopts']}")]
			    }
			}
			stage('covscan vs pacemaker 2.1') {
			    steps {
				build job: "${project}-build-covscan",
				    parameters: [string(name: 'install', value: "${info['install']}"),
						 string(name: 'ghprbActualCommit', value: "${info['actual_commit']}"),
						 string(name: 'ghprbPullId', value: "${info['pull_id']}"),
						 string(name: 'ghprbTargetBranch', value: "${info['target_branch']}"),
						 string(name: 'pcmkver', value: '2.1'),
						 string(name: 'covoptions', value: "${info['covopts']}")]
			    }
			}
			stage('rpm builds') {
			    steps {
				build job: "${project}-build-rpms",
				    parameters: [string(name: 'ghprbActualCommit', value: "${info['actual_commit']}"),
						 string(name: 'ghprbPullId', value: "${info['pull_id']}"),
						 string(name: 'ghprbTargetBranch', value: "${info['target_branch']}"),
						 string(name: 'publishrpm', value: "${info['install']}"),
						 string(name: 'publishprrpm', value: "${info['publish_pr_rpm']}"),
						 string(name: 'bootstrap', value: '0')]
			    }
			}
			stage('non-voting vs pacemaker main') {
			    steps {
				script {
				    try {
					build job: "${project}-build-all-nonvoting",
					    parameters: [string(name: 'ghprbActualCommit', value: "${info['actual_commit']}"),
							 string(name: 'ghprbPullId', value: "${info['pull_id']}"),
							 string(name: 'ghprbTargetBranch', value: "${info['target_branch']}"),
							 string(name: 'pcmkver', value: 'main')]
				    }
				    catch (err) {
					nonvoting_fail++
				    }
				}
			    }
			}
			stage('non-voting vs pacemaker 2.1') {
			    steps {
				script {
				    try {
					build job: "${project}-build-all-nonvoting",
					    parameters: [string(name: 'ghprbActualCommit', value: "${info['actual_commit']}"),
							 string(name: 'ghprbPullId', value: "${info['pull_id']}"),
							 string(name: 'ghprbTargetBranch', value: "${info['target_branch']}"),
							 string(name: 'pcmkver', value: '2.1')]
				    }
				    catch (err) {
					nonvoting_fail++
				    }
				}
			    }
			}
		    }
		}
	    }
	}
    }
    post {
	success {
	    // Notify interested users if non-voting jobs fail
	    script {
		postFunctions(['project': project, 'state': 'success', 'nonvoting_fail': nonvoting_fail, 'voting_fail': voting_fail])
	    }
	}
	failure {
	    // Notify interested users if voting jobs fail
	    script {
		postFunctions(['project': project, 'state': 'failure', 'nonvoting_fail': nonvoting_fail, 'voting_fail': voting_fail])
	    }
	}
    }
}
