// ---------------------------------------------------------------------------
// seed.groovy - Job DSL seed script for ci.kronosnet.org
//
// Generates one multibranch pipeline job per project under pipelines/projects/.
// Each job scans the project's UPSTREAM repo (GitHub or GitLab) for branches
// and PRs/MRs, but the pipeline definition (Jenkinsfile) is read from THIS
// ci-tools repo via the Remote Jenkinsfile Provider (RJP) plugin.
//
// Run this from a "Process Job DSLs" build step pointing at pipelines/seed.groovy.
//
// Requires plugins:
//   - job-dsl
//   - github-branch-source        (GitHub scanning)
//   - gitlab-branch-source        (GitLab scanning)
//   - remote-file / Remote Jenkinsfile Provider (RJP)   -> Jenkinsfile from ci-tools
// ---------------------------------------------------------------------------

// The ci-tools repo that holds the project Jenkinsfiles (this repo).
def CITOOLS_REMOTE = 'https://github.com/kronosnet/ci-tools.git'
def CITOOLS_BRANCH = 'main'

// Jenkins credentials IDs used by the branch sources / RJP checkout.
// Adjust to match your Jenkins credential store.
def GITHUB_CREDS = 'github-app'      // GitHub App or user token credential
def GITLAB_CREDS = 'gitlab-token'    // GitLab API token credential (Secret text)
def GITLAB_SERVER = 'gitlab.com'     // gitlab-branch-source "server name"

// ---------------------------------------------------------------------------
// Per-project configuration.
//
// key   = job name (matches pipelines/projects/<key>/Jenkinsfile)
// scm   = 'github' | 'gitlab'
// owner = org/group that owns the upstream repo
// repo  = upstream repository name
//
// NOTE: owners/repos below are best-effort - verify each against the real
//       upstream location before enabling in production.
// ---------------------------------------------------------------------------
def projects = [
    'anvil':            [scm: 'github', owner: 'ClusterLabs',  repo: 'anvil'],
    'booth':            [scm: 'github', owner: 'ClusterLabs',  repo: 'booth'],
    'corosync':         [scm: 'github', owner: 'corosync',     repo: 'corosync'],
    'corosync-qdevice': [scm: 'github', owner: 'corosync',     repo: 'corosync-qdevice'],
    'dlm':              [scm: 'gitlab', owner: 'linux-cluster', repo: 'dlm'],
    'fence-agents':     [scm: 'github', owner: 'ClusterLabs',  repo: 'fence-agents'],
    'gfs2-utils':       [scm: 'gitlab', owner: 'linux-cluster', repo: 'gfs2-utils'],
    'kernel-ark':       [scm: 'github', owner: 'ClusterLabs',  repo: 'kernel-ark'],
    'kronosnet':        [scm: 'github', owner: 'kronosnet',    repo: 'kronosnet'],
    'kubesan':          [scm: 'github', owner: 'kubesan',      repo: 'kubesan'],
    'libqb':            [scm: 'github', owner: 'ClusterLabs',  repo: 'libqb'],
    'pacemaker':        [scm: 'github', owner: 'ClusterLabs',  repo: 'pacemaker'],
    'pcs':              [scm: 'github', owner: 'ClusterLabs',  repo: 'pcs'],
    'resource-agents':  [scm: 'github', owner: 'ClusterLabs',  repo: 'resource-agents'],
    'sbd':              [scm: 'github', owner: 'ClusterLabs',  repo: 'sbd'],
    // CI self-test projects
    'knet-ci-test-github': [scm: 'github', owner: 'kronosnet', repo: 'knet-ci-test'],
    'knet-ci-test-gitlab': [scm: 'gitlab', owner: 'kronosnet', repo: 'knet-ci-test'],
]

// ---------------------------------------------------------------------------
// Generate a multibranch pipeline job for each project.
// ---------------------------------------------------------------------------
projects.each { jobName, cfg ->

    def scriptPath = "pipelines/projects/${jobName}/Jenkinsfile"

    multibranchPipelineJob(jobName) {
        displayName(jobName)
        description("Auto-generated by seed.groovy. Upstream: ${cfg.scm}:${cfg.owner}/${cfg.repo}. Jenkinsfile: ${scriptPath} (from ci-tools).")

        branchSources {
            branchSource {
                source {
                    if (cfg.scm == 'github') {
                        github {
                            id("${jobName}-github")
                            credentialsId(GITHUB_CREDS)
                            repoOwner(cfg.owner)
                            repository(cfg.repo)
                            configuredByUrl(false)
                            // Discover branches, PRs from origin and forks
                            traits {
                                gitHubBranchDiscovery { strategyId(1) }        // exclude branches that are also filed as PRs
                                gitHubPullRequestDiscovery { strategyId(1) }   // merge PR with target branch
                                gitHubForkDiscovery {
                                    strategyId(1)
                                    trust { gitHubTrustPermissions() }
                                }
                            }
                        }
                    } else {
                        gitLabSCMSource {
                            id("${jobName}-gitlab")
                            serverName(GITLAB_SERVER)
                            credentialsId(GITLAB_CREDS)
                            projectOwner(cfg.owner)
                            projectPath("${cfg.owner}/${cfg.repo}")
                            traits {
                                gitLabBranchDiscovery { strategyId(1) }
                                gitLabOriginDiscovery { strategyId(1) }        // MRs from origin
                                gitLabForkDiscovery {
                                    strategyId(1)
                                    trust { gitLabTrustMembers() }
                                }
                            }
                        }
                    }
                }
            }
        }

        // Discard old branch builds
        orphanedItemStrategy {
            discardOldItems {
                numToKeep(20)
            }
        }

        // Periodic re-scan as a safety net alongside webhooks
        triggers {
            periodicFolderTrigger {
                interval('1d')
            }
        }

        // ------------------------------------------------------------------
        // Skip triggering a build when the head commit message contains a
        // CI-skip token. Uses the "Pipeline: Multibranch build strategy
        // extension" plugin (multibranch-build-strategy-extension).
        // ExcludeMessageBranchBuildStrategy has no @Symbol, so inject the
        // build strategy as raw config XML. excludedMessages is a regex
        // matched with find(); one regex covers both [ci skip] and [skip ci].
        // ------------------------------------------------------------------
        configure { node ->
            def bs = node / sources / 'data' / 'jenkins.branch.BranchSource' / 'buildStrategies'
            bs << 'com.igalg.jenkins.plugins.multibranch.buildstrategy.ExcludeMessageBranchBuildStrategy' {
                excludedMessages('\\[(ci skip|skip ci)\\]')
            }
        }

        // ------------------------------------------------------------------
        // Read the Jenkinsfile from ci-tools instead of the scanned repo,
        // using the Remote Jenkinsfile Provider plugin. RJP has no native
        // DSL, so we swap the project factory node directly.
        // ------------------------------------------------------------------
        configure { node ->
            def factory = node / factory
            factory.@class = 'org.jenkinsci.plugins.workflow.multibranch.RemoteJenkinsFileWorkflowBranchProjectFactory'
            factory.children().each { factory.remove(it) }
            factory << {
                localMarker('')
                remoteJenkinsFile(scriptPath)
                remoteJenkinsFileSCM(class: 'hudson.plugins.git.GitSCM', plugin: 'git') {
                    userRemoteConfigs {
                        'hudson.plugins.git.UserRemoteConfig' {
                            url(CITOOLS_REMOTE)
                            credentialsId(GITHUB_CREDS)
                        }
                    }
                    branches {
                        'hudson.plugins.git.BranchSpec' {
                            name("*/${CITOOLS_BRANCH}")
                        }
                    }
                    doGenerateSubmoduleConfigurations(false)
                    submoduleCfg(class: 'list')
                    extensions()
                }
                matchBranches(false)
                lookupInParameters(false)
            }
        }
    }
}
