// Jenkinsfile for the booth project

@Library(['GlobalLib@fab-devel', 'GithubLib', 'ProjectLib']) _

// Who we are
def project = 'booth'
def info = [:]

// Pipeline code starts here
pipeline {
    // Start on the main Jenkins node. Build jobs are distributed inside 'parallel' below
    agent { label 'built-in' }

    // Things that external jobs might want to influence
    parameters {
	string(name: 'bootstrap',   defaultValue: '0', description: 'Bootstrap the RPM repos')
	string(name: 'fullrebuild', defaultValue: '0', description: 'This is a full rebuild - do not publish RPM and do NOT update build code on the nodes')
    }

    stages {
	// First check we are allowed to run, then set some params for that run
	stage('Setup build env') {
	    steps {
		script {
		    getBuildInfo(project, info)
		}
	    }
	}

        // This is the main stage - building and testing
	stage('Main stage') {
	    when {
		// getAuthCheck (in getBuildInfo) will usually abort the job if permission is denied,
		// but this is an extra check.
		expression { info['authcheck'] == true && info['is_draft'] == false }
	    }

	    // All of the stages that actually do stuff
	    steps {
		script {
		    cleanWs(disableDeferredWipeout: true, deleteDirs: true)

		    voting_pmain = buildRunMap('pmain-voting', info, ['voting': true,
								      'nodelabel': 'voting',
								      'excludes': 'freebsd.*',
								      'extravars': ['depbuildname': 'pacemaker',
										    'depbuildversion': 'main']])
		    voting_pstable = buildRunMap('pstable-voting', info, ['voting': true,
									  'nodelabel': 'voting',
									  'excludes': 'freebsd.*',
									  'extravars': ['depbuildname': 'pacemaker',
											'depbuildversion': '3.0']])
		    voting_poldstable = buildRunMap('poldstable-voting', info, ['voting': true,
										'nodelabel': 'voting',
										'excludes': 'freebsd.*',
										'extravars': ['depbuildname': 'pacemaker',
											      'depbuildversion': '2.1']])

		    nonvoting_pmain = buildRunMap('pmain-nonvoting', info, ['voting': false,
									    'nodelabel': 'nonvoting',
									    'excludes': 'freebsd.*',
									    'extravars': ['depbuildname': 'pacemaker',
											  'depbuildversion': 'main']])
		    nonvoting_pstable = buildRunMap('pstable-nonvoting', info, ['voting': false,
										'nodelabel': 'nonvoting',
										'excludes': 'freebsd.*',
										'extravars': ['depbuildname': 'pacemaker',
											      'depbuildversion': '3.0']])
		    nonvoting_poldstable = buildRunMap('poldstable-nonvoting', info, ['voting': false,
										      'nodelabel': 'nonvoting',
										      'excludes': 'freebsd.*',
										      'extravars': ['depbuildname': 'pacemaker',
												    'depbuildversion': '2.1']])

		    nonvoting_clang_pmain = buildRunMap('pmain-nonvoting-clang', info, ['voting': false,
											'nodelabel': 'nonvoting-clang',
											'excludes': 'freebsd.*',
											'extravars': ['compiler': 'clang',
												      'depbuildname': 'pacemaker',
												      'depbuildversion': 'main',
												      'install': 0]])
		    nonvoting_clang_pstable = buildRunMap('pstable-nonvoting-clang', info, ['voting': false,
											    'nodelabel': 'nonvoting-clang',
											    'excludes': 'freebsd.*',
											    'extravars': ['compiler': 'clang',
													  'depbuildname': 'pacemaker',
													  'depbuildversion': '3.0',
													  'install': 0]])
		    nonvoting_clang_poldstable = buildRunMap('poldstable-nonvoting-clang', info, ['voting': false,
												   'nodelabel': 'nonvoting-clang',
												   'excludes': 'freebsd.*',
												   'extravars': ['compiler': 'clang',
														 'depbuildname': 'pacemaker',
														 'depbuildversion': '2.1',
														 'install': 0]])

		    covscan_pmain = buildRunMap('pmain-covscan', info, ['voting': true,
									'nodelabel': 'covscan',
									'extravars': ['depbuildname': 'pacemaker',
										      'depbuildversion': 'main']])
		    covscan_pstable = buildRunMap('pstable-covscan', info, ['voting': true,
									    'nodelabel': 'covscan',
									    'extravars': ['depbuildname': 'pacemaker',
											  'depbuildversion': '3.0']])
		    covscan_poldstable = buildRunMap('poldstable-covscan', info, ['voting': true,
										  'nodelabel': 'covscan',
										  'extravars': ['depbuildname': 'pacemaker',
												'depbuildversion': '2.1']])

		    buildrpms_pmain = buildRunMap('pmain-buildrpms', info, ['voting': true,
									    'nodelabel': 'buildrpms',
									    'extravars': ['depbuildname': 'pacemaker',
											  'depbuildversion': 'main']])
		    buildrpms_pstable = buildRunMap('pstable-buildrpms', info, ['voting': true,
										'nodelabel': 'buildrpms',
										'extravars': ['depbuildname': 'pacemaker',
											      'depbuildversion': '3.0']])
		    buildrpms_poldstable = buildRunMap('poldstable-buildrpms', info, ['voting': true,
										      'nodelabel': 'buildrpms',
										      'extravars': ['depbuildname': 'pacemaker',
												    'depbuildversion': '2.1']])

		    // Run them (errors are caught in info[:])
		    try {
			parallel voting_pmain + voting_pstable + voting_poldstable +
			    nonvoting_pmain + nonvoting_pstable + nonvoting_poldstable +
			    nonvoting_clang_pmain + nonvoting_clang_pstable + nonvoting_clang_poldstable +
			    buildrpms_pmain + buildrpms_pstable + buildrpms_poldstable +
			    covscan_pmain + covscan_pstable + covscan_poldstable
		    } catch (err) {
			println("Jenkinsfile caught "+err)
			info['exception_text'] += "\nparallel error caught: {$err}\n"
		    }
		}
	    }
	}

        // Build the RPM/Coverity repos etc. If the job failed, this is what tells Jenkins
	stage('Post Stage') {
	    when {
		expression { info['authcheck'] == true && info['is_draft'] == false }
	    }
	    steps {
		postStage(info)
	    }
	}
    }

    // Finish up and send emails
    post {
	always {
	    projectFinishUp(info)
	}
    }
}
