// Jenkinsfile for the a knet CI main project
//  1-May-2023    Chrissie Caulfield    original version for running 'old-style' jobs
// 16-Jun-2023    me again              Move a lot of stuff into getBuildInfo() for tidiness

@Library(['GlobalLib@try-a-map', 'ProjectLib@try-a-map']) _

// Globals
def project = 'ci-test'
def draft_override = '0'
def voting_fail =0
def nonvoting_fail = 0

pipeline {
    agent { label 'built-in' }

    stages {
	// First check we are allowed to run, then set some params for that run
	stage('Setup build env') {
	    steps {
		script {
		    info = getBuildInfo(project, draft_override)
		}
	    }
	}

	// This is the main stage that covers everything
	stage('Start builds') {
	    when {
		// getAuthCheck will usually abort the job if permission is denied
		// but this is an extra check!
		expression { info['authcheck'] == true && info['is_draft'] == false }
	    }
	    // All of the stages that actually do stuff
	    stages {
		stage('Standard builds') {
		    parallel {
			stage('voting') {
			    steps {
				build job: "${project}-build-all-voting",
				    parameters: [string(name: 'install', value: "${info['install']}"),
						 string(name: 'ghprbActualCommit', value : "${info['actual_commit']}"),
						 string(name: 'ghprbPullId', value : "${info['pull_id']}"),
						 string(name: 'ghprbTargetBranch', value : "${info['target_branch']}"),
						 string(name: 'compiler', value : 'gcc')]
			    }
			}
			stage('non-voting') {
			    steps {
				script {
				    try {
					build job: "${project}-build-all-nonvoting",
					    parameters: [string(name: 'install', value: "${info['install']}"),
							 string(name: 'ghprbActualCommit', value : "${info['actual_commit']}"),
							 string(name: 'ghprbPullId', value : "${info['pull_id']}"),
							 string(name: 'ghprbTargetBranch', value : "${info['target_branch']}"),
							 string(name: 'compiler', value : 'gcc')]
				    }
				    catch (err) {
					nonvoting_fail++
				    }
				}
			    }
			}
			stage('covscan') {
			    steps {
				build job: "${project}-build-covscan",
				    parameters: [string(name: 'install', value: "${info['install']}"),
						 string(name: 'ghprbActualCommit', value : "${info['actual_commit']}"),
						 string(name: 'ghprbPullId', value : "${info['pull_id']}"),
						 string(name: 'ghprbTargetBranch', value : "${info['target_branch']}"),
						 string(name: 'covoptions', value : "${info['covopts']}")]
			    }
			}
			stage('buildrpms') {
			    steps {
				script {
				    try {
					build job: "${project}-build-rpms",
					    parameters: [string(name: 'ghprbActualCommit', value : "${info['actual_commit']}"),
							 string(name: 'ghprbPullId', value : "${info['pull_id']}"),
							 string(name: 'ghprbTargetBranch', value : "${info['target_branch']}"),
							 string(name: 'publishrpm', value : "${info['install']}"),
							 string(name: 'publishprrpm', value : "${info['publish_pr_rpm']}"),
							 string(name: 'bootstrap', value : '0')]
				    } catch (err) {
					nonvoting_fail++
				    }
				}
			    }
			}
		    }
		}
	    }
	}
    }
    post {
	success {
	    // Notify interested users if non-voting jobs fail
	    script {
		postFunctions(['project': project, 'state': 'success', 'nonvoting_fail': nonvoting_fail, 'voting_fail': voting_fail])
	    }
	}
	failure {
	    // Notify interested users if voting jobs fail
	    script {
		postFunctions(['project': project, 'state': 'failure', 'nonvoting_fail': nonvoting_fail, 'voting_fail': voting_fail])
	    }
	}
    }
}
