// Update BaseOS on all apk nodes

@Library(['GlobalLib@ilias-devel', 'ProjectLib@ilias-devel']) _

def info = [:]
def project = 'update-all-apk'

// Generate the run-list
def buildFullRunMap(Map info)
{
    def collectBuildEnv = [:]
    def nodeList = getUpNodesByLabel(info['packager'])

    for (def n in nodeList) {
	def node = n
	def realnode = n
	// add exception for alpine-x86-64 that needs to run on built-in node via ansible
	if (node == 'tb-alpine-x86-64') {
	    node = 'built-in'
	}
	collectBuildEnv[node] = {
	    updateOSNode(node, info, realnode)
	}
    }

    return collectBuildEnv
}

pipeline {
    agent { label 'built-in' }

    stages {
        stage('update BaseOS') {
            steps {
		script {
		    info['project'] = project
		    info['packager'] = 'apk'
		    getBuildInfoCommon(info)
		    info['state'] = 'success'
		    info['branch'] = ''
		    info['stages_run'] = 0
		    info['stages_fail'] = 0
		    info['stages_fail_nodes'] = ''

		    // Now do all of the other nodes
		    def updates = buildFullRunMap(info)
		    try {
			parallel updates
			info['state'] = 'completed'
		    } catch (err) {
			println("Jenkinsfile caught "+err)
			info['exception_text'] += "\nparallel error caught: {$err}\n"
			info['state'] = 'error'
		    }
		}
	    }
        }
    }

    // Finish up and send emails
    post {
	always {
	    projectFinishUp(info)
	}
    }
}
