// Update anvil cache on all anvil-bm nodes

@Library(['GlobalLib', 'ProjectLib']) _

def info = [:]
def project = 'anvil-build-cache'

// Generate the run-list
def buildFullRunMap(Map info)
{
    def collectBuildEnv = [:]
    def nodeList = getLabelledNodes('anvil-bm')
    def downnodes = getLabelledNodes('down')
    println('"Down" nodes: '+downnodes)

    for (n in nodeList) {
	def node = n
	if (!downnodes.contains(node)) {
	    collectBuildEnv[node] = {
		anvil_update_node_cache(node, info)
	    }
	}
    }

    return collectBuildEnv
}

pipeline {
    agent { label 'built-in' }

    stages {
        stage('update anvil-bm cache') {
            steps {
		script {
		    info['project'] = project
		    getBuildInfoCommon(info)
		    info['state'] = 'success'
		    info['branch'] = ''
		    info['stages_run'] = 0
		    info['stages_fail'] = 0
		    info['stages_fail_nodes'] = ''

		    // Now do all of the other nodes
		    def updates = buildFullRunMap(info)
		    try {
			parallel updates
			info['state'] = 'completed'
		    } catch (err) {
			println("Jenkinsfile caught "+err)
			info['exception_text'] += "\nparallel error caught: {$err}\n"
			info['state'] = 'error'
		    }
		}
	    }
        }
    }

    // Finish up and send emails
    post {
	always {
	    projectFinishUp(info)
	}
    }
}
