// Jenkinsfile for building anvil kmods

@Library(['GlobalLib', 'ProjectLib']) _

// Globals
def project = 'anvil'

String[] distros = ['rhel-8', 'centos-8-stream', 'rhel-9', 'centos-9-stream']

pipeline {
    agent { label 'built-in' }

    options {
	timeout(time: 60, unit: 'MINUTES')
	skipDefaultCheckout(true)
    }

    stages {
	stage('Update cache matrix') {
	    matrix {
		agent {
		    label "${PLATFORM}"
		}
		axes {
		    axis {
			name 'PLATFORM'
			values 'anvil-ci-bm-phy01', 'anvil-ci-bm-phy02', 'anvil-ci-bm-phy03', 'anvil-ci-bm-phy04'
		    }
	        }

		stages('Update cache node') {
		    stage('Update cache') {
			steps {
			    script {
				stage("Prep build env ${PLATFORM}") {
				    cleanWs(disableDeferredWipeout: true, deleteDirs: true)
				    sh """
					DEST=${project} /root/ci-tools/ci-destroy-anvil-bm-vm
				    """
			    	}
				for (distro in distros) {
				    def state = 'success'
				    stage("Build cache ${PLATFORM} ${distro}") {
					try {
					    sh """
						DEST=${project} /root/ci-tools/ci-setup-anvil-bm-vm-cache ${distro} none none
					    """
					}
					catch(err) {
					    state = 'failure'
					}
					postFunctions(['project': project, 'state': state, 'branch': "cache ${PLATFORM} ${distro}"])
				    }
				}
				stage("Clean build env ${PLATFORM}") {
				    cleanWs(disableDeferredWipeout: true, deleteDirs: true)
				    sh """
					DEST=${project} /root/ci-tools/ci-destroy-anvil-bm-vm
				    """
				}
			    }
			}
		    }
		}
	    }
	}
    }
}
