// Jenkinsfile for the ha-functional-testing

@Library(['GlobalLib@fab-devel', 'VaporLib@fab-devel', 'ProjectLib']) _

def project = 'ha-functional-testing'
def projectid = 'haft'
def info = [:]

pipeline {
    agent { label "${provider}" }

    options {
	skipDefaultCheckout(true)
    }

    stages {
	stage('Prepare test cluster') {
	    steps {
		script {
		    getBuildInfo(project, projectid, info)
		    // apply any overrides here
		    // prep default test cluster
		    prep_test_cluster(info)
		}
	    }
	}
	stage('Run tests') {
	    steps {
		script {
		    run_functional_tests(info)
		}
	    }
	}
    }

    post {
	always {
	    post_functional_tests(info)
	}
    }
}
