// Jenkinsfile for the gfs2-utils project

@Library(['GlobalLib@fab-devel', 'GitlabLib@fab-devel', 'ProjectLib@fab-devel']) _

// Globals
def project = 'gfs2-utils'
def info = [:]

pipeline {
    agent { label 'built-in' }

    options {
	gitLabConnection('gitlab-knet-ci-bot')
	gitlabBuilds(builds: ['jenkins-ci'])
    }

    triggers {
	gitlab(triggerOnPush: true, triggerOnMergeRequest: true)
    }

    parameters {
	string(name: 'bootstrap',   defaultValue: '0', description: 'Bootstrap the RPM repos')
	string(name: 'fullrebuild', defaultValue: '0', description: 'This is a full rebuild - do not publish RPM and do NOT update build code on the nodes')
    }

    stages {
	// First check we are allowed to run, then set some params for that run
	stage('Setup build env') {
	    steps {
		script {
		    getBuildInfo(project, info)
		    updateGitlabStatus(info, [state: 'running', description: 'Jenkins build started'])
		}
	    }
	}
	// This is the main stage that covers everything
	stage('Main stage') {
	    when {
		// getAuthCheck will usually abort the job if permission is denied
		// but this is an extra check!
		expression { info['authcheck'] == true && info['is_draft'] == false }
	    }
	    steps {
		script {
		    cleanWs(disableDeferredWipeout: true, deleteDirs: true)

		    def voting = buildRunMap('voting', info, ['voting': true,
							  'nodelabel': 'voting',
							  'excludes': 'freebsd.*'])

		    def nonvoting = buildRunMap('nonvoting', info, ['voting': false,
								'nodelabel': 'nonvoting',
								'excludes': 'freebsd.*'])

		    def nonvoting_clang = buildRunMap('nonvoting-clang', info, ['voting': false,
									    'nodelabel': 'nonvoting-clang',
									    'excludes': 'freebsd.*',
									    'extravars': ['compiler': 'clang',
											  'install': 0]])

		    def covscan = buildRunMap('covscan', info, ['voting': true,
							    'nodelabel': 'covscan'])

		    def buildrpms = buildRunMap('buildrpms', info, ['voting': true,
								'nodelabel': 'buildrpms'])

		    try {
			parallel voting + nonvoting + nonvoting_clang + buildrpms + covscan
		    } catch (err) {
			println("Jenkinsfile caught "+err)
			info['exception_text'] += "\nparallel error caught: {$err}\n"
		    }
		}
	    }
	}
	stage('Post stage') {
	    when {
		// getAuthCheck will usually abort the job if permission is denied
		// but this is an extra check!
		expression { info['authcheck'] == true && info['is_draft'] == false }
	    }
	    steps {
		postStage(info)
	    }
	}
    }
    post {
	failure {
	    script {
		updateGitlabStatus(info, [state: 'failed', description: 'Jenkins build failed'])
	    }
	}
	success {
	    script {
		updateGitlabStatus(info, [state: 'success', description: 'Jenkins build succeeded'])
	    }
	}
	aborted {
	    script {
		updateGitlabStatus(info, [state: 'canceled', description: 'Jenkins build was canceled'])
	    }
	}
	always {
	    projectFinishUp(info)
	}
    }
}
